"""Current cinematic/roster surface ownership; later weekly mechanics remain explicit proposals."""
import json
from pathlib import Path

def render_cinematic_console():
    root=Path(__file__).resolve().parents[3]
    assets=json.loads((root/'apps/lab/lib/assets/generated/loopforge-focused.json').read_text())['assets']
    image=assets['leadership-call']['variants'][-1]['src']
    return f'''<header class="section-head"><span class="kicker">Interface hierarchy / current refinement</span><h2>Different jobs. Different stages.</h2><p>The camera wall is the operational overview. It does not repeat the roster, the briefing or the leadership call.</p></header>
    <div class="callout"><strong>Start → weekly call → factory → adviser roster → appoint → morning brief → placements → shift.</strong> Adviser appointment remains the first meaningful decision. Inspecting a candidate or reopening the mandate sends no world command.</div>
    <figure><img src="{image}" alt="Loopforge leadership concept: three executive robots facing the director" loading="lazy" style="width:100%;max-height:560px;object-fit:contain"><figcaption>New leadership concept for review. The playable call overlays live captions and confirmed figures in the darker lower area.</figcaption></figure>
    <h3>The factory wall</h3><p>Six stable monitors fill the workspace: two powered, four empty glass screens with tape names. Compact facts, quota and one next action stay around the edge. A receipt briefly marks its source camera, then remains in Records. Short grain drift and restrained tracking interference give the powered glass life without inventing production.</p>
    <h3>Five advisers, one considered choice</h3><p>A stable roster gives every available supervisor a portrait token and short current pitch. Selecting one opens their larger identity and a focused priority, gain and cost. Appointment is explicit. Two are available on day one; three channels await arrival. The author study presents all five with sample pitches and disabled appointment, so later density can be reviewed now. Wider future rosters scroll without shrinking the portraits or expanding into five simultaneous briefings.</p>
    <h3>Leadership takes over the screen</h3><p>No camera frame, instrument strip or beacon. Original artwork fills the viewport, framed by an uneven transparent soot asset and a darker caption region. Opening handover and quota are short separate topics. A future weekly review must use a real completed-week record; the current first-day slice does not invent one.</p>
    <h3>Motion with a purpose</h3><p>Proposed and implemented timing for review: 650 ms scene fade, a single 1.1-second art settle, 320 ms topic change, 240 ms return. No forced reading delay. Reduced motion removes travel; atmosphere-off leaves a complete still composition. These are Loopforge tuning values, not measured Frostpunk timings.</p>
    <p><a href="https://news.xbox.com/en-us/2021/07/21/how-the-visual-identity-of-frostpunk-changed/" target="_blank" rel="noopener">11 bit studios’ visual-design account</a> describes coal-like story-screen splashes and weathered framing. We adapt that material logic to soot, worn brass and Loopforge’s robot world; no Frostpunk assets are shipped.</p>
    <h3>Console light cadence</h3><p>After 12 quiet seconds: one 2.8-second cyan revolution, no more often than every 18 seconds and at least 6 seconds after another signal. Clicks and keys reset inactivity; mouse movement does not starve it. Green follows confirmed production; red follows actual losses; amber marks a decision or a ready line. Most time stays dark. Hidden pages and covered reading surfaces do not animate behind the player’s task.</p>
    <p class="document-links"><a href="/stepanoskin/loopforge/play">Play the current flow ↗</a> · <a href="/stepanoskin/loopforge/play/console-study">Five-person / six-camera study ↗</a> · <a href="LIVING_CONSOLE_DIRECTION.md" download>Hierarchy and research</a> · <a href="CINEMATIC_INTERFACE_DIRECTION.md" download>Cinematic choreography</a> · <a href="LEADERSHIP_CALL_ART.md" download>Concept prompt and provenance</a></p>'''
