"""Current cinematic/roster surface ownership; later weekly mechanics remain explicit proposals."""
import json
from pathlib import Path

def render_cinematic_console():
    root=Path(__file__).resolve().parents[3]
    assets=json.loads((root/'apps/lab/lib/assets/generated/loopforge-focused.json').read_text())['assets']
    image=assets['leadership-call']['variants'][-1]['src']
    return f'''<header class="section-head"><span class="kicker">Interface hierarchy / four integrated consoles</span><h2>Different jobs. Different stages.</h2><p>The producer console is the operational overview. It does not repeat the roster, the briefing or the leadership call. All four skins are implemented; runtime checks and visual calibration are underway.</p></header>
    <div class="callout"><strong>Start → producer console → Answer leadership → cinematic call → Acknowledge quota → console → Choose adviser → roster → appoint → morning brief → placements → shift.</strong> The incoming receiver is the sole opening gameplay action. Early close leaves gameplay locked; settings, mute and exit remain usable. Skin changes and menu/resume preserve acknowledgement and drafts. Inspecting a candidate or reopening the mandate sends no world command.</div>
    <figure><img src="{image}" alt="Loopforge leadership scene: three executive robots facing the director" loading="lazy" style="width:100%;max-height:560px;object-fit:contain"><figcaption>Retained full-screen leadership artwork. The call overlays live captions and confirmed figures in the darker lower area.</figcaption></figure>
    <h3>The factory wall</h3><p>One continuous producer console contains six camera positions: two powered, four empty glass screens with tape names. Compact facts, quota and one next action stay around the edge. The receiver is the sole gameplay action until the opening mandate is acknowledged. Thereafter, a receipt briefly marks its source camera, then remains in Records. Short grain drift and restrained tracking interference give the powered glass life without inventing production.</p>
    <h3>Five advisers, one considered choice</h3><p>A stable roster gives every available supervisor a portrait token and short current pitch. Selecting one opens their larger identity and a focused priority, gain and cost. Appointment is explicit. Two are available on day one; three channels await arrival. The author study presents all five with sample pitches and disabled appointment, so later density can be reviewed now. Wider future rosters scroll without shrinking the portraits or expanding into five simultaneous briefings.</p>
    <h3>Leadership takes over the screen</h3><p>After the player answers the physical receiver: no camera frame, instrument strip or beacon. Original artwork fills the viewport, framed by an uneven transparent soot asset and a darker caption region. Opening handover and quota are short separate topics. A future weekly review must use a real completed-week record; the current first-day slice does not invent one.</p>
    <h3>Motion with a purpose</h3><p>Retained cinematic timing: 650 ms scene fade, a single 1.1-second art settle, 320 ms topic change, 240 ms return. No forced reading delay. Reduced motion removes travel; atmosphere-off leaves a complete still composition. These are Loopforge tuning values, not measured Frostpunk timings. Console hardware motion uses registered fragments cropped via CSS from clean plates; this delivery does not claim separately generated alpha handsets.</p>
    <p><a href="https://news.xbox.com/en-us/2021/07/21/how-the-visual-identity-of-frostpunk-changed/" target="_blank" rel="noopener">11 bit studios’ visual-design account</a> describes coal-like story-screen splashes and weathered framing. We adapt that material logic to soot, worn brass and Loopforge’s robot world; no Frostpunk assets are shipped.</p>
    <h3>Console light cadence and mounting</h3><p>All four skins use their own registered beacon source and local glare; the preceding broad main-console beam is historical. Foundry, Broadcast and porcelain Obedience retain six-pane glass; Dispatch office retains one primary view plus five. Current calibration checks source position, nearby material response and obscured geometry.</p><p>Green follows confirmed production; red follows actual losses; amber marks attention; cyan supplies sparse idle life. Most time stays dark. The earlier 12-second quiet-entry / 18-second repeat cadence is tuning history, not validation of each new profile. Hidden pages and covered reading surfaces stop decorative effects. No winner-selection step is required before delivery.</p>
    <p class="document-links"><a href="/stepanoskin/loopforge/play">Play the current flow ↗</a> · <a href="/stepanoskin/loopforge/play/console-study">Five-person / six-camera study ↗</a> · <a href="LIVING_CONSOLE_DIRECTION.md" download>Hierarchy and research</a> · <a href="CINEMATIC_INTERFACE_DIRECTION.md" download>Cinematic choreography</a> · <a href="LEADERSHIP_CALL_ART.md" download>Concept prompt and provenance</a></p>'''
