"""Current playable composition, kept separate from future mechanics proposals."""
import html

def render_focused_console():
    rows=[
      ('Producer console','Four integrated plate profiles: Foundry, Broadcast, Dispatch with one primary plus five, and porcelain Obedience. Original room feeds, read-only facts and local light; two feeds live, four off.','Start here. Answer leadership is the sole opening gameplay action; after Acknowledge quota, Choose adviser opens the roster.'),
      ('Weekly leadership call','Full-screen original artwork, uneven soot edges, lower captions and confirmed mandate. No console housings or beacon.','Answer receiver → handover → Acknowledge quota → console. Early close preserves the lock; later weeks need real prior performance.'),
      ('Adviser selection','At least five readable roster tokens and short current pitches, with one focused priority/tradeoff panel.','Inspect freely, compare, then explicitly appoint. Day one has two available and three unarrived channels.'),
      ('Intercom and morning brief','A large portrait socket and labelled comic dialogue: factory, other supervisor, priority.','After appointment, hear the structured assessment and then inspect the proposed arrangement.'),
      ('Placement desk','Two room screens and receiving tokens; the adviser’s room carries delegated authority.','Accept or swap, inspect the objection, then authorize.'),
      ('Room focus','One enlarged feed, known operator, condition/output and latest receipt.','Observe the shift here or inspect an attributed action.'),
      ('Incident response','The room report, adviser recommendation and known costs of each response.','Decision pauses. Inspect records without resolving; the pending response remains accessible.'),
      ('Dispatch office','Original dispatch artwork, two destinations and linked worker/quota counters.','Preview locally. Review, then seal an irreversible order.'),
      ('Logistics debrief','Original shipping/logistics artwork, output, wear, losses and supervisor reactions.','Inspect the causal record or begin another first-day playtest.'),
      ('Development and records','Separate capability map and selectable causal receipts.','Future requirements are labelled as design; hidden traits are not exposed.'),
      ('Help, instruments, settings','Recoverable guidance and contextual facts. Only four console skins are selectable; legacy materials remain internal.','Settings, mute and exit remain usable. Acknowledgement and draft choices survive closing, skin switching and menu/resume.'),
    ]
    table=''.join('<tr>'+''.join('<td>'+html.escape(x)+'</td>' for x in row)+'</tr>' for row in rows)
    return '''<header class="section-head"><span class="kicker">Integrated consoles and focused jobs / 8 October</span><h2>One console, then one job at a time.</h2><p>Start reveals one of four integrated consoles and an incoming leadership call. Answering opens the retained cinematic scene; quota acknowledgement releases the internal adviser selector. Roster, briefing, placements, room focus, dispatch and debrief keep their focused compositions.</p></header>
    <div class="callout"><strong>Four skins implemented; runtime checks underway.</strong> The repeated-monitor overview and automatic call are superseded. The old six material choices and mixer are removed from player Settings; matching assets remain internal to focused screens. <a href="index.html#producer-console">Play each console →</a></div><p class="document-links"><a href="/stepanoskin/loopforge/play?console=foundry-desk" target="_blank" rel="noopener">Play the first shift ↗</a> · <a href="/stepanoskin/loopforge/play/console-study" target="_blank" rel="noopener">Historical full-floor density study ↗</a> · <a href="FOCUSED_CONSOLE_REBUILD.md" download>Implementation contract</a></p>
    <div class="table-wrap"><table><thead><tr><th>Job</th><th>What occupies the screen</th><th>Interaction</th></tr></thead><tbody>'''+table+'''</tbody></table></div>
    <h3>Distinct surfaces in one coherent world</h3><p>Leadership takes over the viewport using original full-screen art and soot framing. Its facts and captions occupy the lower area; the console returns after the call. This deliberate visual variation does not change the simulation. The dispatch office is an allocation setting. Shipping/logistics frames the end-of-shift review, and the lobby frames the start menu. These remain outside the six-room management grid. Their reuse preserves the factory’s world while giving each interface a recognizable place.</p>
    <h3>Presentation owns focus; the engine owns facts</h3><p>FirstShift retains acknowledgement, workspace, selected channel, local placements and draft dispatch through Settings, skin changes and menu/resume. Early close never acknowledges the quota. Only validated projections establish world facts; the opening gate adds no engine/API command. Operational views may request advances, while focused reading, dialogs, hidden tabs and menu pause them.</p>
    <h3>Registered hardware and readable text</h3><p>Main-console hardware uses registered fragments cropped via CSS from clean plates, with calibrated feed/control openings and local light. It is not a set of separately generated alpha handsets. Focused screens retain paired internal sockets/controls. Blank tape carries Caveat lettering; speech uses Barlow Semi Condensed; instruments use IBM Plex Mono. Labels and changing facts remain semantic text.</p>
    <h3>Verification still underway</h3><p>Exercise the opening gate and complete first-day loop on all four skins, including skin/menu preservation, desktop/phone bounds, keyboard, sound-off, reduced motion and rendering performance. Historical checks do not establish these new results. The full-floor study is an author-only fixture, not later progression, advanced BDI, live 3D or cloud saves. Owner feedback on the actual game remains decisive.</p>'''
