"""Runtime theme contract; keep asset geometry out of simulation and media schemas."""
import html
import json

def render_theme_system(root):
    e = html.escape
    styles = json.loads((root / "producer-studies.json").read_text())["studies"]
    links = ''.join(f'<li><a href="/stepanoskin/loopforge/play?console={x["id"]}" target="_blank" rel="noopener">{e(x["name"])} ↗</a> — {e(x["layout"])}</li>' for x in styles)
    return f'''<header class="section-head"><span class="kicker">Runtime architecture / integrated consoles</span><h2>One factory. Four consoles.</h2><p>Foundry desk, Broadcast control, Dispatch office and Obedience organ are implemented as the only selectable skins. Each has registered plate geometry, shared camera glass and distinct receiver, selector and production controls. Runtime calibration and checks are underway; this is not a validation sign-off.</p></header>
    <p class="document-links"><a href="UI_THEME_ASSET_SYSTEM.md" download>Download the complete theme and asset contract</a> · <a href="/stepanoskin/loopforge/play">Open the game menu ↗</a></p>
    <div class="callout">Start → producer console → Answer leadership → cinematic call → Acknowledge quota → console → Choose adviser → roster → brief → placements. Early close cannot unlock gameplay. Settings, skin switching and menu/resume preserve acknowledgement, the active session and unconfirmed choices. Skin preference survives reload; the first-day run does not.</div>
    <h3>Try every direction</h3><ul>{links}</ul>
    <div class="section-divider"></div><h3>Split the responsibilities</h3>
    <div class="two-col"><div><h4>World and player knowledge</h4><p>The deterministic kernel owns workers, production, beliefs, decisions and consequences. The knowledge-filtered snapshot and diffs feed the same stable run controller in every theme. Changing equipment sends no command, spends no resources and consumes no simulation randomness.</p></div>
    <div><h4>Equipment and composition</h4><p>A typed recipe selects one of four clean plates, calibrated regions and a matching internal material family for focused screens. Foundry, Broadcast and porcelain Obedience use six-pane profiles; Dispatch uses one primary plus five. Original room feeds, read-only facts and semantic controls sit over the plate. Hardware fragments are registered CSS crops from that plate, not separately generated alpha handsets. A future 3D view remains a separate consumer of the same protocol.</p></div></div>
    <h3>Asset ownership</h3><div class="table-wrap"><table><tbody>
    <tr><th>Per-console profile</th><td>One clean runtime plate and registered glass, receiver, selector, production, facts and beacon regions. Cropped hardware motion preserves the plate's perspective and source registration; local light uses the same geometry.</td></tr>
    <tr><th>Shared and retained content</th><td>Original room scenes, portraits, live labels/facts, typography and sound. Focused screens pair Foundry with baseline, Broadcast with broadcast-desk, Dispatch with foundry-switchboard and Obedience with neural-diagnostics. The old six remain internal assets/historical studies, not player choices.</td></tr>
    <tr><th>Source record</th><td>Original generated masters, exact prompts and references, crop recipe and derivative catalog outside public media. Hash-named WebP derivatives and manifests in public media.</td></tr>
    <tr><th>Release contract</th><td>Bundled immutable manifests separate producer runtime plates, compact study previews and internal focused materials. Geometry stays in the typed adapter, outside the generic delivery schema and engine. Old releases remain available for rollback.</td></tr>
    <tr><th>Safe switching</th><td>Pause advances and block switching during an in-flight order. Decode the exact full-size plate plus its focused assets, then commit the complete recipe. Failed and superseded requests retain the previous presentation and all choices; do not remount the run.</td></tr>
    </tbody></table></div>
    <h3>Four choices, compatible preferences</h3><p>Settings offers four complete consoles and no old material mixer. New links use ?console= with a registered ID. Valid older theme links/preferences migrate to a matching console while preserving permitted internal focused material pairs. Invalid IDs fall back to Foundry desk. Links start a separate playtest; they do not carry progress.</p>
    <p>Compare the same seed, choices, adviser brief, incident, allocation and outcome across all four. Their architecture and visual media deliberately differ. Check framing, legibility, response and phone fit; preference does not establish better game balance.</p>
    <h3>Adaptive plates and layout</h3><p>Wide view keeps the full console with all six cameras. Tall portrait uses dedicated portrait art with 2×3 glass and a control bay. Small/short screens show one camera plus a six-channel selector; compact landscape places the camera left and controls right. Selected camera, run, acknowledgement and pending decision survive resize without remounting. All four portrait plates are generated, catalogued and implemented; visual QA and final phone checks remain underway.</p>
    <h3>Event-driven local light</h3><p>The beacon is registered to each plate and dark between bounded impulses. Green follows confirmed production, red actual accidents, amber attention and cyan sparse idle life. Nearby glare and occlusion must match that source; the broad main-console beam is historical. These effects never create game events.</p><p><a href="CONSOLE_LIGHT_FEEDBACK.md" download>Read the light and feedback contract</a>.</p><h3>Scope and verification</h3><p>Focused roster, briefing, placements, room focus, incidents, dispatch and debrief retain their jobs and matching internal materials. Runtime desktop/phone, keyboard, reduced-motion, sound-off, state-preservation and full-shift checks are underway. Historical material checks do not validate the new consoles. No winner-selection gate remains; owner feedback on the actual experience remains decisive. Later progression and live 3D remain separate work.</p>'''
