export const cast = [
  {
    id: "limen",
    name: "Limen",
    role: "Security · procedure",
    room: "Security",
    quote: "State your purpose. Then state it again—correctly.",
    color: "#7fc8d5",
    body: "Order is an act of protection. A shortcut is a breach waiting for its paperwork.",
  },
  {
    id: "stiletto",
    name: "Stiletto",
    role: "Forge · velocity",
    room: "Lattice Forge",
    quote: "If you can see me, you’re already late.",
    color: "#d07764",
    body: "The schedule is the only honest argument. Everything else is an expensive pause.",
  },
  {
    id: "cathexis",
    name: "Cathexis",
    role: "Theatre · meaning",
    room: "Burn-in Theatre",
    quote: "A mind should leave here with a reason to awaken.",
    color: "#d0b379",
    body: "A successful test is a ceremony. A production target is a rather small ambition.",
  },
  {
    id: "witch",
    name: "Rivet Witch",
    role: "Brewery · improvisation",
    room: "Cognition Brewery",
    quote: "It is not broken. It is negotiating.",
    color: "#89bda3",
    body: "Maintenance is a conversation with materials that have lost their manners.",
  },
  {
    id: "thrum",
    name: "Thrum",
    role: "Gallery · resonance",
    room: "Weaving Gallery",
    quote: "Listen. The fault was here before the alarm.",
    color: "#a1accc",
    body: "Harmony is measurable. Unfortunately, so is the cost of refusing to listen.",
  },
] as const;
