export const linkedInUrl = "https://ca.linkedin.com/in/stepan-oskin-871b8a65";

export const sources = [
  { id: "google", title: "Rules of Machine Learning", publisher: "Google for Developers · Martin Zinkevich", url: "https://developers.google.com/machine-learning/guides/rules-of-ml", note: "Instrumentation, simple baselines, pipeline testing, and the distinction between an optimization objective and the health of the product. See Rules 2, 4, 5, 13, and 39." },
  { id: "microsoft", title: "Patterns of Trustworthy Experimentation", publisher: "Microsoft Experimentation Platform · 2021", url: "https://www.microsoft.com/en-us/research/articles/patterns-of-trustworthy-experimentation-during-experiment-stage/", note: "Overall objectives, local diagnostics, data-quality checks, guardrails, stable segments, and repeated testing. “Getting numbers is easy; getting numbers you trust is hard”—quoted there from Kohavi, Tang, and Xu." },
  { id: "duolingo", title: "Duolingo Launches 148 New Language Courses", publisher: "Duolingo · 30 April 2025 · PDF", url: "https://investors.duolingo.com/node/10901/pdf", note: "A documented example of generative AI, shared content, and internal tooling used to expand a learning catalog across language pairs." },
  { id: "roblox", title: "Accelerating Creation, Powered by Roblox’s Cube Foundation Model", publisher: "Roblox · February 2026", url: "https://about.roblox.com/newsroom/2026/02/accelerating-creation-powered-roblox-cube-foundation-model", note: "Interactive 3D generation connects the appearance of an asset with its behavior. Broader scene-generation ambitions are described as future work." },
  { id: "adobe", title: "GenStudio for Performance Marketing: Insights", publisher: "Adobe · Product documentation", url: "https://experienceleague.adobe.com/en/docs/genstudio-for-performance-marketing/user-guide/insights/overview", note: "Content-level performance analysis connected to the creation of new variants. A concrete example of feedback informing production." },
  { id: "asa", title: "Statement on Statistical Significance and P-Values", publisher: "American Statistical Association · 7 March 2016 · PDF", url: "https://www.amstat.org/asa/files/pdfs/p-valuestatement.pdf", note: "The hero distinguishes effect size, uncertainty and later value. Statistical significance “does not measure the size of an effect or the importance of a result.” Decisions need context beyond a p-value threshold." },
  { id: "pace", title: "Sample sizes required", publisher: "NIST / SEMATECH · Engineering Statistics Handbook", url: "https://www.itl.nist.gov/div898/handbook/prc/section2/prc222.htm", note: "At fixed variability, larger samples narrow uncertainty; required sample size depends on detectable effect, power and the chosen error rate. At fixed traffic, shorter tests collect less evidence." },
  { id: "fdr", title: "Treatment Effect Assessment at Scale", publisher: "Microsoft Experimentation Platform · 15 July 2026", url: "https://www.microsoft.com/en-us/research/articles/treatment-effect-assessment-at-scale-accounting-for-correlated-metrics-and-metric-relevance-in-modern-experimentation/", note: "Multiple comparisons need an explicit false-discovery policy. FDR concerns the expected fraction of false discoveries among discoveries; it is not the probability that an individual result is false. More speed alone does not determine FDR." },
] as const;

export const scenarios = [
  { id: "education", label: "Education", unit: "A learning activity", description: "An explanation, its illustrations, interactive behavior, and assessment form one versioned experience.", local: "Errors, hint use, completion, and performance on a later assessment.", global: "Durable learning and sustained, productive participation.", guardrail: "Content correctness, accessibility, and frustration.", decision: "Compare a revised explanation with the baseline; look for transfer to a later task before calling it a learning gain.", pitfall: "Finishing faster can mean the activity became easier—not that the learner understood more." },
  { id: "games", label: "Games", unit: "A playable encounter", description: "Rules, rewards, visual assets, and difficulty settings are released together as a testable version.", local: "Attempts, failure patterns, voluntary replay, and player feedback.", global: "Long-term player satisfaction and a sustainable game economy.", guardrail: "Fairness, progression balance, and technical performance.", decision: "Test a pacing or feedback change while checking effects on later progression and the rest of the economy.", pitfall: "More attempts can reflect enthusiasm or confusion. The same event count can mean very different things." },
  { id: "commerce", label: "Commerce", unit: "An interactive product selector", description: "Product data, explanatory visuals, and compatibility rules help someone choose the right item.", local: "Completed selections, qualified purchases, and subsequent returns.", global: "Contribution margin from successful, suitable purchases.", guardrail: "Recommendation accuracy, returns, and support demand.", decision: "Compare a new selection flow over a window long enough to include returns; check displacement of other products.", pitfall: "A conversion gain can disappear when returns, service costs, or cannibalized sales are included." },
  { id: "operations", label: "Operations", unit: "A troubleshooting guide", description: "Approved procedures become visual instructions and branching diagnostic steps for a recurring problem.", local: "Verified resolution, repeat contacts, and escalation outcomes.", global: "Reliable service resolution at a sustainable operating cost.", guardrail: "Correctness, escalation access, and customer effort.", decision: "Compare guide versions using verified resolution and follow-up contacts, with a clear path to human support.", pitfall: "Fewer support contacts can mean resolution—or that asking for help became harder." },
] as const;
