export const portfolio = [
  {id:"cod", title:"Call of Duty", subtitle:"The annual blockbuster", poster:"cod-cover", play:"cod-hud", tone:"copper",
    alt:"Official Black Ops 6 reveal artwork with the seated soldier and game title",
    playAlt:"Black Ops 6 pre-release first-person gameplay, with a weapon, minimap, match score and ammunition counter",
    claim:"A new release can sell millions of copies—and become a reason to join a subscription.",
    origin:"Original Call of Duty: Infinity Ward, 2003.", marks:["infinity-ward-logo","treyarch-logo","raven-logo"],
    credit:"Pictured: Black Ops 6 (2024), led by Treyarch and Raven Software; published by Activision. © Activision Publishing, Inc.",
    reading:"A match has opponents, a score and a clock. The annual premium release sits alongside repeat multiplayer sessions; the franchise also includes free-to-play Warzone and mobile games.",
    source:"https://www.callofduty.com/blog/2024/06/call-of-duty-black-ops-6-worldwide-reveal-announcement"},
  {id:"diablo", title:"Diablo", subtitle:"The continuing adventure", poster:"legacy-d4-key", play:"legacy-d4-corridor", tone:"crimson",
    alt:"Diablo IV promotional artwork with Lilith above the game’s title",
    playAlt:"Diablo IV character in the Hell-Touched Corridors with health, abilities and the surrounding dungeon visible",
    claim:"A paid adventure supports an ongoing relationship through seasons, expansions and optional cosmetics.",
    origin:"Original Diablo: Blizzard North, released 1996/97.", marks:["blizzard-logo"],
    credit:"Pictured: Diablo IV, developed and published by Blizzard Entertainment. Original series: Blizzard North. © Blizzard Entertainment, Inc.",
    reading:"The character carries equipment and abilities into the next encounter. Diablo IV sells the base adventure and further offers; its mobile relative Diablo Immortal uses free-to-play entry.",
    source:"https://news.blizzard.com/en-us/article/23816415/diablo-iv-quarterly-updateaugust-2022"},
  {id:"candy", title:"Candy Crush", subtitle:"The game already on the phone", poster:"candy-poster", play:"candy-phone", tone:"rose",
    alt:"King’s Candy Crush Saga artwork with its gold title, brightly colored sweets and confectionery houses",
    playAlt:"King’s App Store promotional screenshot: Candy Crush board, move allowance, lives and boosters, with the publisher’s original slogan",
    claim:"Free entry reaches an audience without asking it to buy a console—or a copy of the game.",
    origin:"Candy Crush Saga: King, Facebook and mobile, 2012.", marks:["king-logo"],
    credit:"Developed and published by King. © King.com Ltd. King joined Activision Blizzard in 2016 and Microsoft in 2023.",
    reading:"A finite number of moves gives this small board its challenge. The promotional view shows the setting for optional assistance, rather than the price of a whole game. It is King’s composed store promotion, not a raw play capture.",
    source:"https://apps.apple.com/us/app/candy-crush-saga/id553834731"},
] as const;
export const portfolioAssets = [...new Set(portfolio.flatMap(item=>[item.poster,item.play,...item.marks]))];
