import type { Chapter, EvidenceSource } from "./types";
import { chapterVisuals } from "./visual-content";

export const parts = ["The fork", "Why the industry built it", "Why people play", "The machine", "Four goods", "The purchase path", "What the instrument cannot read"];
export const revision = "2026-10-01";
export const sources: EvidenceSource[] = [
  { id: "expedition", title: "Sandfall Interactive — Clair Obscur: Expedition 33", url: "https://www.expedition33.com/", note: "Official description of the RPG, available editions and free Thank You Update (December 2025)." },
  { id: "koster", title: "Raph Koster — A Theory of Fun, authorized excerpt", url: "https://www.theoryoffun.com/excerpt.shtml", note: "A design argument connecting fun with learning and understanding patterns; not a universal empirical law." },
  { id: "yee", title: "Nick Yee — Motivations for Play in Online Games (2006)", url: "https://www.nickyee.com/pubs/Yee%20-%20Motivations%20%282006%29.pdf", note: "A survey-based model of achievement, social and immersion motivations in MMORPG play. Its population and genre limit generalization." },
  { id: "mda", title: "Hunicke, LeBlanc & Zubek — MDA (2004)", url: "https://www.cs.northwestern.edu/~hunicke/MDA.pdf", note: "A framework connecting rules, play behavior and intended experience; not a causal revenue model." },
  { id: "sdt", title: "Ryan, Rigby & Przybylski — The Motivational Pull of Video Games (2006)", url: "https://selfdeterminationtheory.org/SDT/documents/2006_RyanRigbyPrzybylski_MandE.pdf", note: "Four studies examine need satisfaction, enjoyment, preference, well-being and future play." },
  { id: "juul", title: "Jesper Juul — The Open and the Closed (2002)", url: "https://jesperjuul.net/text/openandtheclosed.html", note: "Emergence and authored progression can coexist within a game." },
  { id: "outer", title: "Mobius Digital — Separating the Signal from the Noise (2016)", url: "https://www.mobiusdigitalgames.com/news/separating-the-signal-from-the-noise", note: "The developer describes signalscope revisions that make clues easier to interpret. Images are prototypes." },
  { id: "season", title: "Blizzard — Season of the Malignant (2023)", url: "https://news.blizzard.com/en-us/article/23976339/season-of-the-malignant-now-live", note: "Historical explanation of Seasonal and Eternal realms. Current character-creation text is shown separately." },
  { id: "reliquary", title: "Blizzard — Belial’s Return / Reliquaries (2025)", url: "https://news.blizzard.com/en-us/article/24189530/combat-deception-in-season-8-belials-return", note: "Dated launch rules: catalog access, earned Favor, a 99-token held balance, and bundle eligibility. Not a current-season price quote." },
  { id: "auction", title: "Blizzard — Diablo III Auction House Update (2013)", url: "https://news.blizzard.com/en-gb/article/10974978/diablo-iii-auction-house-update", note: "Blizzard said the auction houses undermined the core loot experience and announced their March 2014 removal." },
  { id: "concord", title: "PlayStation — An Important Update on Concord (2024)", url: "https://blog.playstation.com/2024/09/03/an-important-update-on-concord/", note: "Launch on August 23; September 3 notice announces September 6 shutdown and refunds. Does not establish development cost or total sales." },
  { id: "concord-reveal", title: "PlayStation — Concord gameplay revealed (2024)", url: "https://blog.playstation.com/2024/05/30/concord-gameplay-revealed-launching-august-23-2024-on-ps5-and-pc/", note: "Publisher gameplay reveal and provenance for the PS5 capture available only in the local research edition. A historical image, not a currently playable service." },
  { id: "sony", title: "Sony — Game & Network Services investor presentation (2022)", url: "https://www.sony.com/en/SonyInfo/IR/library/presen/irday/pdf/2022/GNS_E.pdf", note: "Historical portfolio plans, including a forecast for live-service franchises. A forecast is not a delivered outcome." },
  { id: "halo", title: "Halo — Season 2: Lone Wolves launch (2022)", url: "https://www.halowaypoint.com/news/season-2-lone-wolves-launch", note: "Documents continuing access to premium passes; free-track access has different rules." },
  { id: "drg", title: "Ghost Ship Games — Reactivating seasons Q&A (2024)", url: "https://steamcommunity.com/games/DeepRockGalactic/announcements/detail/4195740093438639601", note: "Announced season selection and retained track progress. The illustrated proposal is explicitly work in progress." },
  { id: "warframe", title: "Digital Extremes — Collect and Customize guide", url: "https://www.warframe.com/en/news/collect-and-customize-guide", note: "Explains collecting equipment, blueprints, crafting, purchasing and inventory slots." },
  { id: "trade", title: "Digital Extremes — Trading FAQ", url: "https://support.warframe.com/hc/en-us/articles/200092259-Trading-FAQ-Safe-Trading-Tips", note: "Documents tradeable Platinum and restrictions, including non-tradeable promotional currency." },
  { id: "poe", title: "Grinding Gear Games — Premium stash tabs", url: "https://www.pathofexile.com/forum/view-thread/3227486", note: "Public tabs and pricing connect storage convenience to trade. This does not mean all trading requires a paid tab." },
  { id: "experiment", title: "Microsoft Research — Pitfalls of Long-Term Online Controlled Experiments (2016)", url: "https://www.microsoft.com/en-us/research/publication/pitfalls-of-long-term-online-controlled-experiments/", note: "Discusses threats to interpreting long-running experiments and changes in effects over time." },
  { id: "goods", title: "Lehdonvirta — Virtual Item Sales as a Revenue Model (2009)", url: "https://vili.lehdonvirta.com/files/Lehdonvirta%202009%20Virtual%20Item%20Sales%20as%20a%20Revenue%20Model.pdf", note: "Functional, hedonic and social attributes of virtual goods. The four-goods taxonomy here is our analytical lens." },
  { id: "gauntlet", title: "Atari — Gauntlet operator manual (1985)", url: "https://files.stardustarcade.com/PDF_Arcade_Atari_Kee/Gauntlet/Gauntlet_TM-284_1st_Printing.pdf", note: "Original operator documentation, hosted by a public archive. Printed pages 2-3 and 3-4 discuss earnings and health-per-coin settings." },
  { id: "tf2", title: "Valve — Team Fortress 2 becomes free to play (2011)", url: "https://www.teamfortress.com/post.php?id=5721", note: "A documented business-model transition, not an invention claim." },
  { id: "dota", title: "Valve — The International Compendium (2013)", url: "https://www.dota2.com/international2013/compendium/?l=english", note: "Tournament participation, rewards and prize-pool funding preceded many later pass designs." },
  { id: "crossy", title: "Hall & Sum — Crossy Road, GDC (2015)", url: "https://media.gdcvault.com/gdc2015/presentations/Hall_Matthew_Crossy_Road_Whale.pdf", note: "Developer retrospective on optional rewarded video and character purchases; a historical design example." },
  { id: "bg3", title: "Larian — Baldur’s Gate 3", url: "https://baldursgate3.game/", note: "Official product description explicitly states no microtransactions." },
  { id: "elden", title: "Bandai Namco — Shadow of the Erdtree", url: "https://www.bandainamcoent.com/games/elden-ring/shadow-of-the-erdtree", note: "An expansion requiring the Elden Ring base game." },
  { id: "witcher", title: "CD PROJEKT RED — The Witcher 3 Complete Edition (2022)", url: "https://press.cdprojektred.com/en/news/1130/the-witcher-3-wild-hunt-complete-edition-slays-its-way-onto-next-gen", note: "Historical bundle with Hearts of Stone, Blood and Wine and 16 DLC releases. Not a claim about every later edition." },
  { id: "cyberpunk", title: "CD PROJEKT — Phantom Liberty expenditure disclosure (2023)", url: "https://www.cdprojekt.com/en/investors/regulatory-announcements/current-report-no-38-2023/", note: "Separates expansion production and marketing expenditure. Neither figure is a budget for repairing the base game." },
];

const manuscript: Omit<Chapter,"visual">[] = [
  {
    id: "the-fork", part: 0, title: "The fork",
    lede: "Every revenue model makes a different request of the person holding the controller.",
    paragraphs: [
      "A box asks for a purchase before the experience is known. A subscription asks for another period of access. An item shop asks the player to find something worth buying inside a game they already inhabit. Advertising adds another customer: someone paying for the player’s attention.",
      "These arrangements change what a studio has reason to build and measure. They do not settle whether the game is generous, absorbing, tedious or exploitative. A premium game can waste time. A service game can sustain a community that people willingly return to for years.",
      "Diablo IV makes the layers unusually visible: a campaign, character progression, seasonal participation, expansions, a cosmetic shop and reward catalogs. The useful question is concrete: when a commercial rule changes, which choices become easier, harder or more urgent for the player?"
    ], takeaway: "Start with what the transaction asks the player to do.",
    panel: { title: "Three exchanges", items: [{ label: "Purchase", text: "Money → access to an experience" }, { label: "Ongoing service", text: "Repeated payment or purchases → continued value" }, { label: "Advertising", text: "Attention → advertiser-funded play" }] },
    figures: [{ asset: "legacy-d4-key", alt: "Diablo IV promotional artwork showing Lilith against a red background", caption: "Diablo IV is the central case, with other games used to test individual mechanisms.", credit: "Blizzard · promotional art from the handoff" }], sources: ["goods", "crossy"], evidence: "The exchange framework is editorial analysis. It does not infer a studio’s private intentions from its business model."
  },
  {
    id: "six-games", part: 0, title: "Six games, different promises",
    lede: "An ending, an expansion and a season solve different design problems.",
    paragraphs: ["Baldur’s Gate 3, Elden Ring, Clair Obscur: Expedition 33, The Witcher 3 and Cyberpunk 2077 offer useful comparisons with Diablo IV. All contain progression. Their characters gain capabilities, their worlds withhold information, and their authors decide when a reward arrives. A finishable campaign is fully capable of sustaining a large system.", "The comparison becomes more useful when purchase structure, content cadence and persistence are separate columns. A paid expansion adds access. A seasonal realm organizes participation. A cosmetic purchase changes appearance. Treating all three as the same thing hides the design decision.", "Commercial success cannot be read from this table. Unit sales are not profit; a development budget is not total expenditure. These examples test what is possible, rather than estimate which model is generally superior."],
    takeaway: "Compare the promise attached to each purchase.",
    table: { caption: "Selected product structures, with historical scope where specified. This is not a current price or complete DLC catalog.", headers: ["Game", "Design emphasis", "Commercial example"], rows: [["Baldur’s Gate 3", "Authored campaign and branching choices", "Base game; Larian states no microtransactions"], ["Elden Ring", "Exploration, combat and build mastery", "Base game + Shadow of the Erdtree"], ["Clair Obscur: Expedition 33", "Authored RPG campaign", "Premium game; no sales or budget estimate used here"], ["The Witcher 3", "Authored quests in an open world", "2022 Complete Edition bundles two story expansions"], ["Cyberpunk 2077", "Authored open-world RPG", "Phantom Liberty as a separately produced expansion"], ["Diablo IV", "Campaign plus repeatable progression", "Base game, expansions, shop and seasonal catalogs"]] }, sources: ["bg3", "elden", "expedition", "witcher", "cyberpunk", "reliquary"], evidence: "The table describes selected products, not a six-game financial experiment. No estimated revenue, undisclosed development budget or claim of permanent offline access is used."
  },
  {
    id: "the-reset", part: 0, title: "Where progress lives",
    lede: "A character can survive a season while losing access to the next season’s starting line.",
    paragraphs: ["Diablo IV separates Seasonal and Eternal participation. The captured character-creation tooltip says the Seasonal character becomes Eternal at season’s end. That is materially different from deleting everything the player earned. A new season can still ask for a fresh climb, even when the previous character remains playable elsewhere.", "Four kinds of persistence help explain the distinction: knowledge in the player, skill in the player, state on a character, and entitlements on an account. They can move on different schedules. A reset of one does not establish a reset of the others.", "Outer Wilds offers a useful counterexample to the assumption that progress must be a rising statistic. Its investigative tools help players connect clues. Understanding changes the next attempt, even when a world repeats. The genres and purposes differ; that difference makes the persistence question clearer."], takeaway: "Name what resets, what persists, and where it remains usable.",
    panel: { title: "Four places change accumulates", items: [{label:"Knowledge",text:"What the player understands"},{label:"Skill",text:"What the player can execute"},{label:"Character",text:"Levels, equipment and quest state"},{label:"Account",text:"Owned access and cosmetics"}] },
    figures: [{asset:"d4-seasonal-tooltip",alt:"Diablo IV Seasonal Character tooltip states that the character becomes Eternal at the end of the season",caption:"The Seasonal tooltip explicitly describes transfer to Eternal. Owner reports the current season and version at capture, 1 October 2026.",credit:"Owner capture · platform/build number unconfirmed"},{asset:"outer-wilds-signalscope-prototype",alt:"Early Outer Wilds signalscope interface facing Riebeck",caption:"The signalscope directs curiosity toward a place to investigate. This image is a 2016 prototype, not the released interface.",credit:"Mobius Digital · 2016 design article"}],sources:["season","outer"],evidence:"The current Rebirth confirmation has not been captured. No exact list of what Rebirth preserves or removes is asserted here."
  },
  {
    id:"several-histories",part:1,title:"Several histories at once",lede:"Commercial tuning existed long before the rotating shop.",
    paragraphs:["Atari’s Gauntlet manual gave arcade operators controls over health per coin and guidance on earnings. Payment and game difficulty were already connected at the cabinet. Later subscriptions, free-to-play item sales, player markets, rewarded advertising and passes developed alongside one another.","Team Fortress 2’s move to free-to-play and Dota 2’s tournament Compendium illustrate different transitions within Valve’s games. Crossy Road’s creators described optional rewarded video as part of their design. None makes the others obsolete.","A single ladder from ‘buy a game’ to ‘buy a pass’ gives history a false destination. The mechanisms remain available together, and a modern game can combine several of them."],takeaway:"A business model is a set of choices, not a historical stage.",
    panel:{title:"Selected historical anchors",flow:true,items:[{label:"1985 · Gauntlet",text:"Coins, health and operator tuning"},{label:"2011 · Team Fortress 2",text:"A shipped game moves to free-to-play"},{label:"2013 · Dota 2",text:"Tournament companion, participation and rewards"},{label:"2015 · Crossy Road talk",text:"Optional video funds some play"},{label:"2022 · Halo policy",text:"Premium tracks remain accessible"},{label:"2025 · Diablo IV",text:"Reliquaries separate access from claiming"}]},
    figures:[{asset:"gauntlet-options-manual-p3-4",alt:"Gauntlet operator manual table with game difficulty and health-per-coin switches",caption:"Health-per-coin settings in the 1985 Gauntlet operator manual, printed page 3-4. A commercial variable is exposed as a game rule.",credit:"Atari · manual preserved by Stardust Arcade"}],sources:["gauntlet","tf2","dota","crossy","halo","reliquary"],evidence:"Dates identify documented examples, not claims about who first invented a mechanism. The timeline is selective rather than a complete global history."
  },
  {
    id:"concord",part:1,title:"Concord",lede:"A multiplayer game has to attract people who can find other people to play with.",
    paragraphs:["Concord launched on 23 August 2024. On 3 September, PlayStation announced it would go offline on 6 September and that purchases would be refunded. That short public sequence is sufficient to establish a severe commercial failure. Speculative budgets are not needed to make it dramatic.","A population-dependent game faces constraints that a solitary campaign does not. Region, mode, skill, platform and time of day divide the available population. A worldwide concurrent-player total cannot by itself tell us whether a particular queue will fill.","The design lesson is to test demand and the service’s ability to function before production commitments remove room to change direction. The announcement cannot tell us which internal decisions were decisive, or isolate price from differentiation, timing and execution."],takeaway:"Test the conditions required for the game to function.",figures:[{asset:"concord-shutdown-announcement-art",alt:"Concord promotional artwork with a group of characters",caption:"Key art accompanying the shutdown announcement. The linked statement, rather than this artwork, establishes the dates and refund policy.",credit:"Firewalk / PlayStation · September 2024"}],sources:["concord","concord-reveal"],evidence:"No unsupported total-sales estimate, development-cost figure or minimum viable player threshold is presented. One failure cannot identify a universal cause."
  },
  {
    id:"what-decides",part:1,title:"What a studio can learn in time",lede:"A production plan needs a way for evidence to change it.",
    paragraphs:["A studio’s tools, accumulated knowledge and working relationships constrain which promises it can keep. A familiar genre may reduce some risks without guaranteeing demand. A new direction can succeed, but the plan must account for what the team still needs to learn.","Early access, prototypes and external playtests expose different risks. People enjoying an opening hour do not establish that a service can sustain a year of updates. Strong sales do not establish that players understood the economy. The test must match the uncertainty.","The useful comparison between a long successful project and a long unsuccessful one is therefore more specific than elapsed time. What could each team observe, when could it observe it, and which decisions were still reversible?"],takeaway:"A milestone should reduce uncertainty, not merely accumulate output.",panel:{title:"A decision can remain reversible",flow:true,items:[{label:"Promise",text:"What experience is being offered?"},{label:"Evidence",text:"Which observation could disprove the plan?"},{label:"Decision",text:"What can still change after that observation?"}]},sources:["mda","experiment"],evidence:"This is a proposed production-review framework. It is not a reconstruction of undisclosed studio decisions or a claim that one development process guarantees success."
  },
  {
    id:"shape-of-money",part:1,title:"The shape of the money",lede:"A continuing revenue stream arrives with continuing obligations.",
    paragraphs:["Premium sales often concentrate around releases, promotions and expansions. Services create repeated opportunities to sell. Their income still depends on player demand, competition, content and operating costs. A recurring offer is not a guaranteed annuity.","Sony’s 2022 investor presentation recorded a planned expansion of its live-service portfolio. It is evidence of a strategy at a particular moment. It does not prove that all public companies prefer the same games or that every project was commissioned for the same reason.","The financial comparison must keep its units straight. Gross sales, platform receipts, marketing, development expenditure and profit answer different questions. CD PROJEKT’s separate disclosures for Phantom Liberty production and marketing show why a single combined ‘budget’ can conceal more than it explains."],takeaway:"Compare revenue together with the cost of keeping the promise.",panel:{title:"Two schematic cost profiles",items:[{label:"Release-led",text:"Production → launch → support and future releases"},{label:"Service-led",text:"Production → ongoing content, operations and acquisition"}]},sources:["sony","cyberpunk"],evidence:"The profiles are conceptual, not measured revenue curves. No valuation multiple or financial return is inferred from a publisher presentation."
  },
  {
    id:"why-people-play",part:2,title:"What players want",lede:"Returning is behavior. The reason for returning still needs to be understood.",
    paragraphs:["Self-determination research examines autonomy, competence and relatedness. Its game studies consider enjoyment and well-being as well as future play. Reducing the theory to a retention model would discard much of what it tries to explain.","Autonomy concerns participation a person endorses; a crowded menu can still feel coercive. Competence concerns effective action; a rising level can accompany little learning. Relatedness concerns connection; a friend list is only one possible route to it.","Koster connects fun with learning patterns; Yee’s MMORPG research distinguishes overlapping achievement, social and immersion motives. These lenses ask different questions from self-determination theory. Together they make one limitation clear: the same completed quest can represent discovery, companionship or an unwanted chore. An event counter cannot distinguish them."],takeaway:"Measure participation and the quality of that participation separately.",panel:{title:"Three questions about the same session",items:[{label:"Autonomy",text:"Did I want to do this?"},{label:"Competence",text:"Could I understand and affect the outcome?"},{label:"Relatedness",text:"Did I feel connected to someone?"}]},sources:["sdt","koster","yee"],evidence:"These questions adapt a researched theory for design discussion. They are not a validated survey instrument and should not be treated as a diagnostic score."
  },
  {
    id:"play-beyond-score",part:2,title:"Play beyond the score",lede:"A counter can be part of an argument about counting.",
    paragraphs:["INDIKA places a score beside a story about belief and doubt. The captured scene asks the player to hold a button to pray. An action, a visual response and a number coexist; their presence does not require the number to be the work’s ultimate purpose.","Calling this a game ‘with no systems’ would miss its rules, inputs, constraints and framing. The more interesting reading is that familiar game language can be used expressively. A reward signal may invite suspicion as well as pleasure.","That interpretation should remain an interpretation. It cannot establish how every player felt, or prove that a theory of motivation fails because a character is distressed. The player’s experience and the character’s situation are different subjects."],takeaway:"A system can produce meaning as well as advancement.",figures:[{asset:"legacy-indika-pray",alt:"INDIKA shows a Hold LT to pray prompt in a red-lit scene",caption:"A held input makes prayer an action the player performs. The screenshot establishes the prompt, not the complete experience of holding it.",credit:"Odd Meter / 11 bit studios · handoff capture, date unknown"},{asset:"legacy-indika-points",alt:"INDIKA shows a glowing reward symbol and a numerical score",caption:"The visible score invites a reading of what is being counted and why. Its expressive role is discussed here as interpretation.",credit:"Odd Meter / 11 bit studios · handoff capture, date unknown"}],sources:["mda","sdt"],evidence:"Close reading of the supplied captures. No invented playthrough, universal emotional response or unsupported claim that every point unlocks nothing is used."
  },
  {
    id:"anatomy-of-loop",part:3,title:"Anatomy of a loop",lede:"The next second and the next month need different reasons to be interesting.",
    paragraphs:["An attack gives immediate feedback. A fight changes the local situation. A session can resolve a quest or improve a build. A longer project might involve learning a role, exploring a world or organizing a group. These rhythms can support each other without being interchangeable.","MDA separates implemented rules, behavior during play and intended experience. Changing a cooldown is a rule change; changing when players retreat is a possible behavioral consequence; tension or relief is an experience to investigate. The final step cannot be established from code alone.","Visual impact and responsive controls can make repetition satisfying. They also communicate whether an action worked. A larger reward animation does not establish that the underlying decision became more interesting."],takeaway:"Follow a rule through behavior to an experience you can investigate.",panel:{title:"Nested reasons to continue",flow:true,items:[{label:"Moment",text:"Act → perceive the result"},{label:"Encounter",text:"Read a situation → adapt"},{label:"Session",text:"Choose and complete a goal"},{label:"Longer project",text:"Learn, explore, build or coordinate"}]},sources:["mda","juul"],evidence:"An original explanatory model. The timescales are illustrative, not measurements of Diablo IV sessions."
  },
  {
    id:"loot-table",part:3,title:"The loot table",lede:"A low chance repeated many times still leaves room for someone to be unlucky.",
    paragraphs:["A random drop system can determine which object appears and which properties it carries. Targeted sources, crafting, trade and guarantees change how the player can respond to an unwanted result. Two systems with the same headline rarity may offer very different control over the search.","The model below assumes independent attempts with a fixed chance. It answers one narrow question: how likely is at least one success after a chosen number of attempts? It does not simulate Diablo IV, paid draws, changing probabilities or a guarantee counter.","A guarantee changes the tail of the distribution. A trade route changes the alternatives. A price changes the stakes. Similar-looking reward animations cannot establish that all these processes share the same rules or consequences."],takeaway:"Describe the actual reward process before assigning it a psychological label.",interactive:"probability",sources:[],evidence:"The calculator uses the mathematical identity P(at least one success) = 1 − (1 − p)ⁿ. All inputs are hypothetical. No drop rate, spending effect or causal claim about compulsion is inferred."
  },
  {
    id:"the-checklist",part:3,title:"The checklist",lede:"A visible goal removes one kind of uncertainty and can introduce another kind of pressure.",
    paragraphs:["A checklist tells a player what the game will recognize. It can introduce unfamiliar activities, make a large world legible or help a group coordinate. It can also direct a session toward an expiring reward rather than the activity the player came to enjoy.","The difference depends on the requirements, the deadline, the reward and the player’s circumstances. A completed list does not establish that the list improved the experience. An abandoned list does not establish that the experience failed.","Separate a season’s release date from the availability of its rewards. Halo’s documented premium-pass policy and Deep Rock Galactic’s announced season-selection design show that a cadence of new content can coexist with continuing access to earlier tracks."],takeaway:"Ask what happens when a player takes a week off.",figures:[{asset:"legacy-season-rank",alt:"Diablo IV Death Awakening season ranks interface with a time remaining indicator",caption:"A historical Death Awakening season screen makes ranks and remaining time visible. It is not evidence of the current season’s objective requirements.",credit:"Blizzard · handoff capture, date unknown"},{asset:"drg-season-selection-proposal-2024",alt:"Deep Rock Galactic proposed season selection menu marked work in progress",caption:"Ghost Ship’s April 2024 season-selection proposal, visibly marked WORK IN PROGRESS. Use the developer’s documented policy separately from the mockup’s exact UI.",credit:"Ghost Ship Games · 2024 proposal"},{asset:"halo-premium-pass-rewards-2022",alt:"Halo Infinite Season 2 promotional reward lineup",caption:"A 2022 promotional reward lineup. The accompanying launch article documents ongoing premium-pass access; the artwork itself does not establish that policy or the free track’s rules.",credit:"343 Industries / Xbox · 2022 promotional art"}],sources:["halo","drg"],evidence:"These policy examples have different scopes. They do not establish that every event, free track or cosmetic remains available indefinitely."
  },
  {
    id:"familiar-verbs",part:3,title:"Familiar verbs, changing decisions",lede:"The same button can ask a different question in a different system.",
    paragraphs:["Diablo II and Diablo IV share recognizable language: an elevated camera, health resources, monsters and equipment. Screenshots make that continuity easy to see. They tell us much less about timing, enemy interactions, build constraints or the decisions a player makes under pressure.","Juul’s account of emergence helps explain why a small vocabulary of actions can produce many situations. A familiar attack can interact with a new enemy, a different resource economy or another player’s role. Novel verbs are one kind of change, not a complete measure of design development.","A useful comparison records what information the player needs, what can go wrong and what alternatives remain. Claims that monetization froze the combat system need stronger evidence than two similar-looking interfaces."],takeaway:"Compare decisions and consequences, as well as visible verbs.",figures:[{asset:"legacy-d2-combat",alt:"Diablo II combat near the Cairn Stones with Rakanishu",caption:"Diablo II: a historical combat interface. The image demonstrates visual vocabulary, not the complete combat system.",credit:"Blizzard · handoff capture, version/date unknown"},{asset:"legacy-d4-corridor",alt:"Diablo IV character in the Hell-Touched Corridors with health and resource displays",caption:"Diablo IV: familiar framing and resources. Understanding the differences requires observing play, builds and encounters.",credit:"Blizzard · handoff capture, version/date unknown"}],sources:["juul"],evidence:"No unmeasured art-budget ratio, input-latency comparison or causal explanation of genre continuity is asserted."
  },
  {
    id:"access",part:4,title:"Access",lede:"Some purchases open a door. The important detail is what is behind it.",
    paragraphs:["A base game, an expansion, a subscription and a catalog unlock can all sell access. They differ in what becomes available and what remains to be done after paying. A campaign may be immediately playable; a reward catalog may still require earned currency for its contents.","The captured Diablo IV campaign selector places campaign choices and locked expansion entries in the same decision. That makes ownership relevant before the character enters the world. It does not establish what percentage of seasonal objectives require an expansion.","Good disclosure names the entitlement, prerequisites and remaining effort together. A player should be able to tell whether a purchase grants a finished item, the opportunity to earn it, or a new activity in which to participate."],takeaway:"Explain what paying unlocks and what it leaves unfinished.",figures:[{asset:"d4-campaign-state",alt:"Diablo IV campaign selection with an Endgame recommendation and locked expansion entries",caption:"Campaign selection captured on 1 October 2026. The owner reports the current version/season; locked entries show this account’s access state.",credit:"Owner capture · build/platform unconfirmed"}],sources:["elden","reliquary"],evidence:"No current expansion price, exact objective-gating percentage or cost of authored campaign production is inferred from this screen."
  },
  {
    id:"identity",part:4,title:"Identity",lede:"Appearance can matter even when nobody else sees it.",
    paragraphs:["A cosmetic item can express a preference, support a character fantasy, complete a collection or communicate status. Those motives can overlap. Calling the purchase ‘only cosmetic’ describes a boundary around mechanical effects; it does not describe the intensity of the player’s desire.","The Diablo IV shop makes identity goods conspicuous through presentation, grouping and rotation. Whether that visibility becomes welcome discovery or unwanted pressure is a player-experience question. The existence of an offer is not evidence that every viewer feels the same thing.","The four lenses used here—access, identity, time and power—are deliberately porous. An appearance may also save time in a collection. An access purchase may introduce a powerful class. Classification should describe the transaction’s effects rather than provide a moral label."],takeaway:"Cosmetic value can be personal, social and aesthetic at once.",figures:[{asset:"legacy-d4-shop-grid",alt:"Diablo IV shop with cosmetic bundles, a refresh countdown and an Ancient Hydra preview",caption:"A historical shop screen groups appearance items and displays a refresh timer. Its offers and prices are not presented as current.",credit:"Blizzard · handoff capture, date unknown"}],sources:["goods"],evidence:"Virtual-goods research supports several kinds of value. Individual motives and the effect of a countdown require evidence beyond a screenshot."
  },
  {
    id:"time",part:4,title:"Time",lede:"Convenience changes the route through a game, and sometimes changes which routes are practical.",
    paragraphs:["Storage, crafting waits, inventory management and travel all occupy time. Paying to alter them can preserve attention for valued play. It can also create an incentive to leave a frustrating route in place. Which description applies depends on the design and on the player’s alternatives.","Warframe illustrates the overlap: equipment can involve blueprints, materials and crafting, while some purchases change the route to ownership. Trading adds another distinction. A player may acquire eligible Platinum from another player without personally buying it; the currency’s wider source still matters.","Path of Exile’s public premium stash tabs connect storage to item pricing and trade visibility. That is more than a purely visual change. It also does not mean all trade is impossible without buying a tab. Describe the actual inconvenience and available route rather than assuming either total freedom or total compulsion."],takeaway:"Compare the paid route with the complete unpaid route.",panel:{title:"One item, several commitments",items:[{label:"Play and craft",text:"Time, materials, knowledge and inventory capacity"},{label:"Purchase",text:"Currency and any remaining prerequisites"},{label:"Trade",text:"Another player, eligible goods and transaction rules"}]},sources:["warframe","trade","poe"],evidence:"A conceptual comparison of documented routes. No current matched-item price, universal earnability claim or exact time-saving estimate is made."
  },
  {
    id:"power",part:4,title:"Power",lede:"A purchase changes power when it changes what the player can accomplish under the game’s rules.",
    paragraphs:["Power is contextual. Damage, survivability, access to options and the ability to bypass a constraint can matter differently in cooperative play, a competitive ladder or a solitary campaign. A label such as ‘pay to win’ is a starting point for specifying the advantage, not a substitute for doing so.","Blizzard’s Diablo III auction-house closure announcement provides a particularly clear historical example. The company said the auction houses undermined the game’s core loot experience. That supports a conflict between acquisition through the market and acquisition through play.","It does not independently establish that drop rates were deliberately made worse to generate marketplace revenue. The documented lesson is narrower and stronger: a commercially useful acquisition route can compete with the activity that gives the reward its meaning."],takeaway:"Name the advantage and the experience it displaces.",panel:{title:"Two routes to the same reward",items:[{label:"Play route",text:"Encounter → uncertainty → acquisition"},{label:"Market route",text:"Search → exchange → acquisition"}]},sources:["auction"],evidence:"The auction-house mechanism is historical. This chapter does not claim that every Diablo title, mode or purchasable entitlement follows the same rules."
  },
  {
    id:"what-things-cost",part:5,title:"What things actually cost",lede:"A currency price and the cash needed at checkout are different quantities.",
    paragraphs:["A virtual-currency price can be simple to compare within a store while requiring another calculation before purchase. The player needs to know their existing balance, available packs, the selected pack’s cash price and the balance left afterwards.","The captured store belongs to a CAD account. Its prices are historical evidence, with an unknown capture date. The example below lets you inspect a single pack purchase against a hypothetical item; it is not a quote for an item currently on sale or an optimizer for every combination of packs.","Unspent currency retains possible future use inside the system. That makes it different from money spent on the present item, while also making it different from cash freely available elsewhere. Show the cash outlay and the remaining balance separately."],takeaway:"Make the cash commitment legible before the currency purchase.",interactive:"price",figures:[{asset:"legacy-d4-platinum",alt:"Diablo IV Platinum packs with cash prices from the owner’s Canadian-dollar store",caption:"Owner identifies the store currency as CAD. Capture date is unknown; use these figures only as a historical illustration.",credit:"Blizzard · owner-provided handoff capture"}],sources:[],evidence:"The calculator uses only visible pack prices, preserves CAD throughout and assumes a zero starting balance. Taxes, regional changes and platform differences are not estimated."
  },
  {
    id:"two-key-lock",part:5,title:"The two-key lock",lede:"Buying access to a reward catalog may leave the rewards to be earned.",
    paragraphs:["Blizzard’s 2025 Reliquary explanation separates access purchased with Platinum from items claimed with earned Favor Tokens. That creates two requirements: the entitlement to use a catalog and the play needed to claim its contents. Free rewards and special bundles require their own treatment.","The same documentation describes 99 as the number of Favor Tokens held at once. Spending some allows more to be earned; up to 99 can carry forward. A catalog whose total cost exceeds 99 therefore does not, by that fact alone, force a cash shortfall.","The useful questions concern the whole path: how Favor is earned, what expires, which items depend on completing a set, and what each bundle grants. Exact current-season prices and eligibility should come from the current interface rather than be carried forward from launch documentation."],takeaway:"A holding cap is not a lifetime earning cap.",panel:{title:"Documented 2025 structure",flow:true,items:[{label:"Platinum",text:"Unlock eligible premium catalog access"},{label:"Play",text:"Earn Favor, up to the held-balance limit"},{label:"Favor",text:"Claim accessible rewards; spending makes room to earn again"}]},figures:[{asset:"legacy-favor-tutorial",alt:"Favor Tokens tutorial explains that players can hold 99 tokens, spend them and earn more",caption:"The tutorial distinguishes the maximum held balance from how much can be earned over time. This is a historical capture.",credit:"Blizzard · handoff capture, date unknown"}],sources:["reliquary"],evidence:"Current Hell’s Legacy bundle details are still awaiting account captures. No launch-era bundle price or bonus rule is silently treated as current."
  },
  {
    id:"abstraction-and-surface",part:5,title:"Abstraction and surface",lede:"An interface can show every number and still leave the decision difficult to understand.",
    paragraphs:["A price, a token balance, an unlock condition and a deadline can sit on separate screens. Each may be technically visible while the total commitment remains difficult to assemble. Evaluating clarity requires following the whole purchase path.","The visual hierarchy matters. A large reward preview can dominate a small requirement. A rotating offer can change when a decision feels necessary. These are interface properties that can be inspected; their effects on spending or regret still need measurement.","A useful design review asks players to explain what they will own after paying, what they must do afterwards, and what happens if they stop. Errors in those answers identify a comprehension problem more directly than simply counting taps to checkout."],takeaway:"Test whether people can explain the transaction in their own words.",panel:{title:"Before confirming",items:[{label:"Ownership",text:"What exactly will become mine?"},{label:"Remaining effort",text:"What must I still earn or complete?"},{label:"Time",text:"What expires, and when?"},{label:"Balance",text:"What cash leaves, and what currency remains?"}]},sources:["reliquary","goods"],evidence:"These are proposed comprehension checks. A screenshot can reveal hierarchy and disclosed terms, but does not by itself demonstrate a causal spending effect."
  },
  {
    id:"does-it-work",part:6,title:"Does any of it work?",lede:"A player who returns and a player who is glad to return can produce the same event.",
    paragraphs:["Retention, purchases, playtime and completed objectives describe behavior. Interviews and well-designed surveys can investigate motives, satisfaction and regret. Revenue and operating cost describe another outcome again. None is a complete substitute for the others.","Experiments can identify causal effects under their design assumptions. Their duration, population, treatment exposure and chosen outcomes constrain what they establish. Microsoft’s research on long-term experiments discusses some of these problems; it does not say that experimentation is incapable of studying enduring value.","The handoff ends with Stepan’s own case: a level-eight Eternal Barbarian named funduck, and uncertainty about how to re-enter the game. One person cannot establish a population result. The case can still identify a concrete design question: does the returning player understand which character, realm and activity will deliver the experience they want?"],takeaway:"A useful metric should leave room for the player’s account of what happened.",panel:{title:"Four kinds of evidence",items:[{label:"Behavior",text:"What did people do?"},{label:"Experience",text:"How did they describe it?"},{label:"Business",text:"What value and costs resulted?"},{label:"Causality",text:"Which change produced which effect?"}]},figures:[{asset:"legacy-d4-char-select",alt:"Diablo IV Season Info popup over the owner’s character selection screen",caption:"The Season Info prompt distinguishes a new seasonal character from continuing in Eternal. This is not the missing Rebirth confirmation.",credit:"Blizzard · owner-provided handoff capture"}],sources:["experiment","sdt"],evidence:"Stepan’s case is attributed to his supplied handoff. Public concurrency cannot identify this individual’s retention or the cause of his decision."
  },
];

// Every chapter has a scene, a conceptual diagram, and a reference screenshot.
export const chapters: Chapter[] = manuscript.map(chapter => {
  const visual=chapterVisuals[chapter.id];
  return {...chapter,visual,figures:[visual.screenshot,...(chapter.figures??[]).filter(figure=>figure.asset!==visual.screenshot.asset)]};
});

export const appendix = [
  "Describe the player’s desired experience before choosing the metric.",
  "Name what is bought, earned, retained and allowed to expire.",
  "Separate character state from player knowledge and account ownership.",
  "Compare the full paid and unpaid routes to the same outcome.",
  "Show cash outlay and leftover currency together.",
  "Treat a holding cap separately from a total earning limit.",
  "Test whether a break from the game remains a comfortable choice.",
  "Match each prototype or experiment to the uncertainty it can reduce.",
  "Keep historical policy, current interface and interpretation visibly distinct.",
  "Measure experience alongside behavior, and costs alongside revenue.",
];
