import type { Figure } from "./types";
export type SceneKind = "gate"|"arena"|"market"|"relic"|"observatory"|"citadel";
export type VisualSpec = {
  scene:SceneKind; sceneTitle:string; sceneCaption:string;
  diagram:{title:string;center:string;nodes:[string,string,string,string];notes:[string,string,string,string];kind:"cycle"|"branch"|"sequence"|"balance";caption:string};
  screenshot:Figure;
};
const shot=(asset:string,alt:string,caption:string,credit="Blizzard"):Figure=>({asset,alt,caption,credit});
const corridor=shot("legacy-d4-corridor","Diablo IV character in the Hell-Touched Corridors","Diablo IV’s encounter space. A frame establishes the interface and scene; the surrounding argument examines the decisions around it.");
const shop=shot("legacy-d4-shop-grid","Diablo IV cosmetic storefront with bundles and a refresh timer","The store puts recurring offers beside the player’s ongoing character. Historical capture; these are not current prices.");
const indika=shot("legacy-indika-pray","INDIKA prayer interaction in a fractured red room","A visible input connects an action to a changing environment. This historical capture is used as a specific visual example.","Odd Meter / 11 bit studios");
const outer=shot("outer-wilds-signalscope-prototype","Outer Wilds early signalscope facing Riebeck","Mobius’s 2016 prototype makes an investigative tool visible. This is a development image, not the final released interface.","Mobius Digital · 2016 design article");
const season=shot("legacy-season-rank","Diablo IV season rank screen with a deadline","A historical Death Awakening screen presents a visible progression track and a remaining-time indicator.");
const tokens=shot("legacy-d4-platinum","Diablo IV Platinum packs and CAD prices","Diablo IV’s Platinum packs, priced in CAD. Historical prices.");
function v(scene:SceneKind,sceneTitle:string,sceneCaption:string,title:string,center:string,nodes:VisualSpec['diagram']['nodes'],notes:VisualSpec['diagram']['notes'],kind:VisualSpec['diagram']['kind'],caption:string,screenshot:Figure):VisualSpec{
  return {scene,sceneTitle,sceneCaption,diagram:{title,center,nodes,notes,kind,caption},screenshot};
}
export const chapterVisuals:Record<string,VisualSpec>={
  "insert-coin":v("market","The coin slot and the dungeon","An original cutaway connects the commercial machine with the world inside it.","What a coin adds","PAID PARTICIPATION",["Coin","Health","Play","Continue"],["The payment","The reserve","The adventure","The next decision"],"cycle","Original cutaway. Settings from Atari’s 1985 operator manual, printed page 3–4.",shot("gauntlet-gameplay-1985","Gauntlet arcade gameplay with health, score and coin prompts","A running adventure and its offer to join share one screen.","Atari Games")),
  "the-fork":v("gate","The business of keeping a world alive","Continuing play, production and payment follow different paths after a purchase.","What continues after a purchase?","AFTER THE SALE",["Player","Studio","Payment","Future"],["What can I keep doing?","What is made next?","Who buys what?","What can change?"],"branch","Three possible arrangements, shown without a financial scale or timetable. A game can combine them; returning to play does not itself create another sale.",shot("bg3-official-key-art","Baldur’s Gate 3 official key art","Larian’s fantasy adventure provides one contemporary example of a substantial release.","Wizards of the Coast / Larian Studios")),
  "six-games":v("citadel","A world with an ending","An authored citadel can contain a vast system while still letting its journey end.","Separate three promises","THE PROMISE",["Access","Cadence","Persistence","Completion"],["What opens?","What arrives later?","What stays?","Can the work end?"],"branch","Compare each product along these dimensions before comparing commercial outcomes.",corridor),
  "the-reset":v("gate","Two realms, one history","A character crosses a threshold; the knowledge held by its player travels differently.","Four places progress lives","PROGRESS",["Knowledge","Skill","Character","Account"],["Understanding","Execution","Local state","Owned entitlements"],"branch","Persistence belongs to several subjects. A change to one does not imply a reset of all four.",shot("d4-seasonal-tooltip","Diablo IV Seasonal Character tooltip describes transfer to Eternal","Owner capture, 1 October 2026: the tooltip explicitly describes the Seasonal character becoming Eternal.","Blizzard")),
  "several-histories":v("market","The old exchange","An imagined arcade of stalls connects payment, access and repeated participation.","What does the next payment buy?","COEXISTENCE",["Participation","A copy","An extra","Attention"],["Extend a paid run","Return to what is owned","Buy within continued play","An advertiser pays"],"sequence","Selected documented anchors. The path is chronology, not an inevitable progression or an invention claim.",shot("legacy-d2-heroes","Diablo II class selection around a campfire","A historical Diablo II character-selection screen: a purchased game can still offer many reasons to replay.")),
  "concord":v("citadel","A city without its crowd","An empty, imagined arena makes the dependency on other players visible.","Concord’s documented window","2024",["23 AUG","3 SEP","6 SEP","REFUNDS"],["Game launched","Closure announced","Servers taken offline","Purchases refunded"],"sequence","The official closure notice supports these milestones. It does not establish budget, total sales or a universal minimum audience.",shot("concord-gameplay-reveal-2024","Concord gameplay screenshot from the May 2024 PlayStation reveal","Firewalk’s May 2024 gameplay reveal. It shows the announced game before launch; the closure timeline is sourced separately.","Firewalk / Sony Interactive Entertainment · PlayStation Blog, 30 May 2024")),
  "what-decides":v("observatory","A question made visible","An instrument in an unfinished chamber represents a prototype built to answer one question.","Learn before commitment grows","UNCERTAINTY",["Question","Prototype","Observation","Decision"],["Name the unknown","Build the smallest probe","Watch relevant behavior","Revise the commitment"],"cycle","A proposed learning loop. A prototype is useful when its result changes a decision.",outer),
  "shape-of-money":v("market","Keep the lights burning","The market’s furnaces stand for the continuing work behind a continuing offer.","Two sides of a service","CONTINUITY",["Player value","Revenue","Operations","New content"],["A reason to return","Funds the promise","Keeps it available","Renews its usefulness"],"cycle","A schematic obligation loop, without invented cash curves or financial results.",shop),
  "why-people-play":v("citadel","A place to return to","Three travelers share an invented courtyard; their reasons for being there need not match.","Beyond the return event","EXPERIENCE",["Autonomy","Competence","Relatedness","Context"],["I endorse this choice","I can affect the outcome","I feel connected","My reasons can change"],"branch","Need satisfaction offers questions about experience; a completed event cannot answer them alone.",shot("legacy-social","Diablo IV social interface","A social interface exposes ways to connect. Its presence alone does not establish a player’s sense of relatedness.")),
  "play-beyond-score":v("observatory","The ritual and its counter","An original ritual chamber places a luminous tally beside an experience that exceeds it.","The counter is not the whole work","MEANING",["Input","Rule","Feedback","Interpretation"],["What I do","What can happen","What the work shows","What I make of it"],"sequence","A close-reading framework. Player meaning cannot be reduced to the visible reward signal.",indika),
  "anatomy-of-loop":v("arena","The next encounter","A traveler confronts an original arena whose threats, routes and reward remain readable.","Nested reasons to continue","PLAY",["Moment","Encounter","Session","Longer project"],["Act / perceive","Read / adapt","Choose / complete","Learn / build / belong"],"cycle","The loops nest rather than share one timescale. This is an explanatory model, not measured session data.",corridor),
  "loot-table":v("relic","The unopened reliquary","One unknown reward waits inside an original chamber of possibilities.","What changes the search?","ACQUISITION",["Randomness","Targeting","Guarantee","Alternatives"],["Which result arrives?","Where can I look?","How bad can luck get?","Can I craft or trade?"],"branch","These rules affect different parts of the acquisition problem. The interactive exhibit isolates fixed independent chance.",shot("legacy-d2-item","Diablo II item tooltip","A historical item tooltip makes properties and rarity tangible. No probability is inferred from this image.")),
  "the-checklist":v("gate","The scheduled threshold","An invented clockwork gate makes a deadline visible above a route through the world.","A deadline is a design choice","THE GOAL",["Requirement","Reward","Deadline","Return path"],["What must be done?","Why do it?","When does it expire?","What if I take a break?"],"branch","A checklist can guide or pressure. Its effect depends on the complete set of rules and the player’s circumstances.",season),
  "familiar-verbs":v("arena","Old movement, new question","An original combat space rearranges obstacles around a familiar action.","From familiar action to new decision","ACTION",["Information","Constraint","Alternatives","Consequence"],["What can I read?","What limits me?","What else can I do?","What changes afterward?"],"cycle","Compare these relationships alongside the visible controls. Similar screenshots do not establish identical systems.",shot("legacy-d2-combat","Diablo II combat near the Cairn Stones","A historical Diablo II encounter gives the comparison a concrete starting frame.")),
  "access":v("gate","What the key opens","Three invented doors separate entry, ownership and remaining effort.","After the payment","ENTITLEMENT",["Purchase","Access","Prerequisite","Remaining effort"],["The cash commitment","The door that opens","What else is required?","What must still be done?"],"sequence","Not every purchase grants a finished item. Disclose what paying opens and what it leaves to complete.",shot("d4-campaign-state","Diablo IV campaign selector with locked expansion entries","The account’s campaign selector shows open and locked choices. Owner capture, 1 October 2026.","Blizzard")),
  "identity":v("relic","An object made personal","An original ceremonial object can be desired for expression, collection or belonging.","Several kinds of cosmetic value","IDENTITY",["Expression","Fantasy","Collection","Social meaning"],["This is my taste","This is my character","This completes a set","This says something"],"branch","These motives can overlap. Cosmetic describes mechanical scope, not how much an appearance matters.",shop),
  "time":v("market","Two routes to an object","An imagined market shows the long material route and a shorter exchange route.","Compare the complete routes","OWNERSHIP",["Play / craft","Purchase","Trade","Constraints"],["Time and materials","Currency commitment","Another player","Slots, waits, prerequisites"],"balance","Convenience has to be evaluated against the actual unpaid alternatives and remaining constraints.",shot("legacy-poe-store","Path of Exile store showing purchasable offerings","A historical Path of Exile store provides the commercial context. The chapter’s stash-tab claim is sourced to developer documentation.","Grinding Gear Games")),
  "power":v("arena","An advantage in context","An original duel asks what a purchased option changes in the encounter.","Two acquisition routes","THE REWARD",["Encounter","Uncertainty","Market search","Exchange"],["Act within the game","Resolve the outcome","Find an available item","Acquire through a transaction"],"balance","A market can compete with the activity that gives its goods meaning. This diagram does not claim manipulated drop rates.",shot("legacy-d2-item","Diablo II item attributes and requirements","Item properties show why acquisition routes can matter to play. This is a Diablo II comparison image, not a Diablo III auction-house capture.")),
  "what-things-cost":v("market","The balance left behind","An original coin chamber separates an item’s price from the currency that remains.","Four quantities at checkout","CASH ≠ TOKENS",["Existing balance","Item price","Pack purchase","Remaining balance"],["What I already hold","What the item needs","What cash must leave","What stays in the system"],"sequence","The interactive illustration holds the starting balance at zero and compares one pack at a time.",tokens),
  "two-key-lock":v("relic","Two keys for one vault","An original twin-lock vault separates permission to claim from the earned resource.","Unlock, earn, claim","TWO REQUIREMENTS",["Platinum","Catalog access","Earned Favor","Claimed reward"],["Paid currency","First requirement","Second requirement","Spend Favor to claim"],"sequence","A simplified historical example. The earning increment and claim price are invented.",shot("legacy-favor-tutorial","Diablo IV Favor Tokens tutorial","The historical tutorial distinguishes a held balance from what can be earned after spending tokens.")),
  "abstraction-and-surface":v("observatory","A transaction in pieces","An original viewing chamber separates four windows that must form one understandable decision.","Can the player explain it?","COMPREHENSION",["Ownership","Effort","Deadline","Cash and balance"],["What becomes mine?","What remains to do?","What can expire?","What leaves and remains?"],"branch","These are proposed comprehension checks. Visual hierarchy can be observed; spending effects require measurement.",shot("legacy-d4-confirm","Diablo IV purchase confirmation interface","This historical confirmation labels the cosmetic FREE, states a weapon-type restriction and shows the remaining Platinum balance. A zero-price claim still uses the purchase interface.")),
  "does-it-work":v("citadel","What the world leaves with you","A traveler leaves an original citadel carrying knowledge beyond its visible counters.","Four kinds of evidence","VALUE",["Behavior","Experience","Business","Causality"],["What did people do?","How did it feel?","What value and cost?","What caused the change?"],"branch","Each instrument answers a different question. Use their differences to improve the interpretation.",shot("legacy-d4-char-select","Diablo IV seasonal information over character selection","The owner’s return to a character-selection screen provides one concrete case, rather than a population result.")),
};
