import type { Figure } from "./types";
export type SceneKind = "gate"|"arena"|"market"|"relic"|"observatory"|"citadel";
export type VisualSpec = {
  scene:SceneKind; sceneTitle:string; sceneCaption:string;
  diagram:{title:string;center:string;nodes:[string,string,string,string];notes:[string,string,string,string];kind:"cycle"|"branch"|"sequence"|"balance";caption:string};
  screenshot:Figure;
};
const shot=(asset:string,alt:string,caption:string,credit="Blizzard"):Figure=>({asset,alt,caption,credit});
const corridor=shot("legacy-d4-corridor","Diablo IV character in the Hell-Touched Corridors","Diablo IV’s encounter space. A frame establishes the interface and scene; the surrounding argument examines the decisions around it.");
const shop=shot("legacy-d4-shop-grid","Diablo IV cosmetic storefront with bundles and a refresh timer","The store puts recurring offers beside the player’s ongoing character. Historical capture; these are not current prices.");
const indika=shot("legacy-indika-pray","INDIKA prayer interaction in a fractured red room","A visible input connects an action to a changing environment. This historical capture is used as a specific visual example.","Odd Meter / 11 bit studios");
const outer=shot("outer-wilds-signalscope-prototype","Outer Wilds early signalscope facing Riebeck","Mobius’s 2016 prototype makes an investigative tool visible. This is a development image, not the final released interface.","Mobius Digital · 2016 design article");
const season=shot("legacy-season-rank","Diablo IV season rank screen with a deadline","A historical Death Awakening screen presents a visible progression track and a remaining-time indicator.");
const tokens=shot("legacy-d4-platinum","Diablo IV Platinum packs and CAD prices","Diablo IV’s Platinum packs, priced in CAD. Historical prices.");
function v(scene:SceneKind,sceneTitle:string,sceneCaption:string,title:string,center:string,nodes:VisualSpec['diagram']['nodes'],notes:VisualSpec['diagram']['notes'],kind:VisualSpec['diagram']['kind'],caption:string,screenshot:Figure):VisualSpec{
  return {scene,sceneTitle,sceneCaption,diagram:{title,center,nodes,notes,kind,caption},screenshot};
}
export const chapterVisuals:Record<string,VisualSpec>={
 "mobile-freemium":v("market","A little game. A very long life.","King’s original art identifies the game; the dated milestone compares its continuing production.","You are already playing.","OPTIONAL PURCHASE",["Enter","Play","Try again","Buy assistance"],["No box price","A puzzle","Wait or return","Moves and boosters"],"branch","Qualitative routes: unpaid play remains possible and no conversion rate is implied.",shot("candy-poster","Candy Crush Saga official promotional artwork","King’s mobile franchise: the entry price and the business behind it are different questions.","King.com Ltd")),
"several-histories":{"scene": "gate", "sceneTitle": "A dungeon within reach", "sceneCaption": "The original game combines a directed descent with changing encounters and equipment.", "diagram": {"title": "What changed around the adventure?", "center": "THE SAME SERIES", "nodes": ["Diablo", "Diablo II", "Diablo III", "Diablo IV"], "notes": ["Discovery", "Replay", "Redesign", "Continuing work"], "kind": "sequence", "caption": "Compare play, production and payment across the series. These are historical mechanisms, not measured cash flows."}, "screenshot": {"asset": "diablo-original-combat", "alt": "Diablo: a warrior inside a crowded stone dungeon, above the health and mana interface", "caption": "The original Diablo: danger, equipment and the character’s resources share one view. The cathedral’s changing rooms lead toward a fixed confrontation.", "credit": "Blizzard Entertainment · authorized GOG gallery", "afterParagraph": 2}},
"diablo-second-life":{"scene": "gate", "sceneTitle": "The road can be travelled again", "sceneCaption": "An authored journey can sustain many builds and a shared restart without selling another run.", "diagram": {"title": "What changed around the adventure?", "center": "THE SAME SERIES", "nodes": ["Diablo", "Diablo II", "Diablo III", "Diablo IV"], "notes": ["Discovery", "Replay", "Redesign", "Continuing work"], "kind": "sequence", "caption": "Compare play, production and payment across the series. These are historical mechanisms, not measured cash flows."}, "screenshot": {"asset": "legacy-d2-heroes", "alt": "Diablo II class selection around a campfire", "caption": "Diablo II’s five original classes offer different ways through the same purchased adventure.", "credit": "Blizzard Entertainment", "afterParagraph": 1}},
"diablo-market":{"scene": "gate", "sceneTitle": "Two routes to the same equipment", "sceneCaption": "A market can supply equipment while weakening the activity that made obtaining it satisfying.", "diagram": {"title": "What changed around the adventure?", "center": "THE SAME SERIES", "nodes": ["Diablo", "Diablo II", "Diablo III", "Diablo IV"], "notes": ["Discovery", "Replay", "Redesign", "Continuing work"], "kind": "sequence", "caption": "Compare play, production and payment across the series. These are historical mechanisms, not measured cash flows."}, "screenshot": {"asset": "diablo-three-items", "alt": "Diablo III rare and legendary boots shown in equipment comparison panels", "caption": "Blizzard’s 2016 retrospective uses this earlier interface to show why a legendary label did not make an item an obvious upgrade. This is equipment comparison, not the auction house.", "credit": "Blizzard Entertainment · Nevalistis, 2016", "afterParagraph": 3}},
"diablo-service":{"scene": "gate", "sceneTitle": "An adventure, and a production calendar", "sceneCaption": "The campaign belongs to a larger program of seasons, expansions, services and optional offers.", "diagram": {"title": "What changed around the adventure?", "center": "THE SAME SERIES", "nodes": ["Diablo", "Diablo II", "Diablo III", "Diablo IV"], "notes": ["Discovery", "Replay", "Redesign", "Continuing work"], "kind": "sequence", "caption": "Compare play, production and payment across the series. These are historical mechanisms, not measured cash flows."}, "screenshot": {"asset": "d4-campaign-state", "alt": "Diablo IV campaign selector with included adventure and expansion access", "caption": "The campaign selector puts different adventures and their access requirements inside one continuing game.", "credit": "Blizzard Entertainment", "afterParagraph": 0}},

  "making-worlds":v("market","The work of making a world","Selected game-world citations and an original factory instrument.","One shift. Two accounts.","RECORDED CONSEQUENCES",["Decision","Simulation","Event","Account"],["Choose","Resolve","Record","Interpret"],"sequence","Recorded prototype outcomes with authored voice studies; no live model call.",shot("witcher-world","Geralt faces a griffin in The Witcher 3","A traversable landscape becomes a place for authored encounters.","CD PROJEKT RED S.A.")),
  "platform-business":v("market","The work behind the offer","Compare the agreements behind the same evening.","Who makes it. Who gets paid.","FOLLOW THE AGREEMENT",["Production","Rights","Distribution","Payment"],["Funds","Licenses","Reaches","Settles"],"sequence","Documented arrangements, not a measured flow.",shot("netflix-wordmark","Netflix wordmark","Netflix identifies one catalog business in the comparison.","Netflix")),
  "cloud-gaming":v("market","A game you own, a machine you hire","Local and remote computing supply the same purchased adventure.","The machine moves; the purchase remains","REMOTE COMPUTING",["Game","Store","Provider","Player"],["Creates","Sells","Renders","Connects"],"sequence","Cloud membership does not replace the game purchase.",shot("cyberpunk-night-city","Cyberpunk 2077: illuminated towers and stacked streets in Night City","Night City’s streets and lighting have to be rendered somewhere—on the player’s machine or a provider’s.","CD PROJEKT RED S.A.")),
  "valve-platform":v("market","Valve: the studio becomes the store","Original business-role illustration","Which business is earning?","FOLLOW THE ROLE",["Studio","Publisher","Store","Player"],["Creates","Releases","Distributes","Chooses"],"branch","Conceptual relationships, not measured cash flows.",shot("half-life-promo","Official Half-Life promotional artwork with its lambda logo, title and Gordon Freeman","Half-Life’s first release preceded Steam by five years; its sequel was sold through Steam as well as retail shops.","Valve Corporation")),
  "epic-infrastructure":v("market","Epic: the studio becomes the engine","Original business-role illustration","Which business is earning?","FOLLOW THE ROLE",["Studio","Publisher","Store","Player"],["Creates","Releases","Distributes","Chooses"],"branch","Conceptual relationships, not measured cash flows.",shot("epic-web-shop","Epic\u2019s official web-shop mockup on desktop and phone","Epic\u2019s web-shop mockup: the infrastructure supplier can sit behind another game\u2019s storefront. This is a promotional interface illustration, not a record of a completed purchase.","Epic Games")),
  "rockstar-world":v("market","Rockstar: worlds built to last","Original business-role illustration","Which business is earning?","FOLLOW THE ROLE",["Studio","Publisher","Store","Player"],["Creates","Releases","Distributes","Chooses"],"branch","Conceptual relationships, not measured cash flows.",shot("rockstar-los-santos","GTA Online Doomsday Heist promotional image with flying vehicles and an aircraft","The Doomsday Heist gives an existing world another spectacle and another reason to gather. This official GTA Online promotional frame is a later addition, not an image of the 2013 campaign launch.","Rockstar Games / Take-Two Interactive")),
  "how-many-lives":v("market","The coin slot and the dungeon","An original cutaway connects the commercial machine with the world inside it.","What a coin adds","PAID PARTICIPATION",["Coin","Health","Play","Continue"],["The payment","The reserve","The adventure","The next decision"],"cycle","Original cutaway. Settings from Atari’s 1985 operator manual, printed page 3–4.",shot("gauntlet-gameplay-1985","Gauntlet arcade gameplay with health, score and coin prompts","A running adventure and its offer to join share one screen.","Atari Games")),
  "insert-coin":v("market","A game in the room","The gathering and the work behind it.","The place around the game","AN EVENING",["Maker","Supplier","Venue","Player"],["Builds","Places","Hosts","Plays"],"sequence","Roles may overlap. An original imagined room, not a historical reconstruction.",shot("pong-cabinet","The yellow production Pong cabinet","Pong’s shared controls and screen turn a simple game into a shared occasion.","Rob Boudon / Ubcule · CC BY 2.0")),
  "studio-to-screen":v("market","The work and its route","The same game can arrive through different businesses.","Follow the work. Follow the receipts.","TO THE PLAYER",["Production","Rights","Distribution","Operation"],["Who funds it?","Who may sell it?","Who reaches us?","Who runs it?"],"sequence","A role map, not a quantitative cash flow. One company can occupy several positions.",shot("cyberpunk-night-city","Cyberpunk 2077: illuminated towers and stacked streets in Night City","Night City in Cyberpunk 2077. Its dense streets and lighting have to be rendered somewhere—on the player’s machine or a provider’s.","CD PROJEKT RED S.A.")),
  "the-fork":v("gate","The business of keeping a world alive","Continuing play, production and payment follow different paths after a purchase.","What continues after a purchase?","AFTER THE SALE",["Player","Studio","Payment","Future"],["What can I keep doing?","What is made next?","Who buys what?","What can change?"],"branch","Three possible arrangements, shown without a financial scale or timetable. A game can combine them; returning to play does not itself create another sale.",shot("bg3-official-key-art","Baldur’s Gate 3 official key art","Larian’s fantasy adventure provides one contemporary example of a substantial release.","Wizards of the Coast / Larian Studios")),
  "six-games":v("citadel","A world with an ending","An authored citadel can contain a vast system while still letting its journey end.","Separate three promises","THE PROMISE",["Access","Cadence","Persistence","Completion"],["What opens?","What arrives later?","What stays?","Can the work end?"],"branch","Compare each product along these dimensions before comparing commercial outcomes.",corridor),
  "the-reset":v("gate","Two realms, one history","A character crosses a threshold; the knowledge held by its player travels differently.","Four places progress lives","PROGRESS",["Knowledge","Skill","Character","Account"],["Understanding","Execution","Local state","Owned entitlements"],"branch","Persistence belongs to several subjects. A change to one does not imply a reset of all four.",shot("d4-seasonal-tooltip","Diablo IV Seasonal Character tooltip describes transfer to Eternal","Owner capture, 1 October 2026: the tooltip explicitly describes the Seasonal character becoming Eternal.","Blizzard")),
  "concord":v("citadel","A city without its crowd","An empty, imagined arena makes the dependency on other players visible.","Concord’s documented window","2024",["23 AUG","3 SEP","6 SEP","29 OCT"],["Game launched","Refunds announced","Service offline","Studio closure"],"sequence","The official closure notice supports these milestones. It does not establish budget, total sales or a universal minimum audience.",shot("concord-gameplay-reveal-2024","Concord gameplay screenshot from the May 2024 PlayStation reveal","Firewalk’s May 2024 gameplay reveal. It shows the announced game before launch; the closure timeline is sourced separately.","Firewalk / Sony Interactive Entertainment · PlayStation Blog, 30 May 2024")),
  "what-decides":v("observatory","A question made visible","An instrument in an unfinished chamber represents a prototype built to answer one question.","Learn before commitment grows","UNCERTAINTY",["Question","Prototype","Observation","Decision"],["Name the unknown","Build the smallest probe","Watch relevant behavior","Revise the commitment"],"cycle","A proposed learning loop. A prototype is useful when its result changes a decision.",outer),
  "shape-of-money":v("market","Keep the lights burning","The market’s furnaces stand for the continuing work behind a continuing offer.","Two sides of a service","CONTINUITY",["Player value","Revenue","Operations","New content"],["A reason to return","Funds the promise","Keeps it available","Renews its usefulness"],"cycle","A schematic obligation loop, without invented cash curves or financial results.",shop),
  "why-people-play":v("citadel","A place to return to","Three travelers share an invented courtyard; their reasons for being there need not match.","Beyond the return event","EXPERIENCE",["Autonomy","Competence","Relatedness","Context"],["I endorse this choice","I can affect the outcome","I feel connected","My reasons can change"],"branch","Need satisfaction offers questions about experience; a completed event cannot answer them alone.",shot("legacy-social","Diablo IV social interface","A social interface exposes ways to connect. Its presence alone does not establish a player’s sense of relatedness.")),
  "play-beyond-score":v("observatory","The ritual and its counter","An original ritual chamber places a luminous tally beside an experience that exceeds it.","The counter is not the whole work","MEANING",["Input","Rule","Feedback","Interpretation"],["What I do","What can happen","What the work shows","What I make of it"],"sequence","A close-reading framework. Player meaning cannot be reduced to the visible reward signal.",indika),
  "anatomy-of-loop":v("arena","The next encounter","A traveler confronts an original arena whose threats, routes and reward remain readable.","Nested reasons to continue","PLAY",["Moment","Encounter","Session","Longer project"],["Act / perceive","Read / adapt","Choose / complete","Learn / build / belong"],"cycle","The loops nest rather than share one timescale. This is an explanatory model, not measured session data.",corridor),
  "loot-table":v("relic","The unopened reliquary","One unknown reward waits inside an original chamber of possibilities.","What changes the search?","ACQUISITION",["Randomness","Targeting","Guarantee","Alternatives"],["Which result arrives?","Where can I look?","How bad can luck get?","Can I craft or trade?"],"branch","These rules affect different parts of the acquisition problem. The interactive exhibit isolates fixed independent chance.",shot("legacy-d2-item","Diablo II item tooltip","A historical item tooltip makes properties and rarity tangible. No probability is inferred from this image.")),
  "the-checklist":v("gate","The scheduled threshold","An invented clockwork gate makes a deadline visible above a route through the world.","A deadline is a design choice","THE GOAL",["Requirement","Reward","Deadline","Return path"],["What must be done?","Why do it?","When does it expire?","What if I take a break?"],"branch","A checklist can guide or pressure. Its effect depends on the complete set of rules and the player’s circumstances.",season),
  "familiar-verbs":v("arena","Old movement, new question","An original combat space rearranges obstacles around a familiar action.","From familiar action to new decision","ACTION",["Information","Constraint","Alternatives","Consequence"],["What can I read?","What limits me?","What else can I do?","What changes afterward?"],"cycle","Compare these relationships alongside the visible controls. Similar screenshots do not establish identical systems.",shot("legacy-d2-combat","Diablo II combat near the Cairn Stones","A historical Diablo II encounter gives the comparison a concrete starting frame.")),
  "access":v("gate","What the key opens","Three invented doors separate entry, ownership and remaining effort.","After the payment","ENTITLEMENT",["Purchase","Access","Prerequisite","Remaining effort"],["The cash commitment","The door that opens","What else is required?","What must still be done?"],"sequence","Not every purchase grants a finished item. Disclose what paying opens and what it leaves to complete.",shot("d4-campaign-state","Diablo IV campaign selector with locked expansion entries","The account’s campaign selector shows open and locked choices. Owner capture, 1 October 2026.","Blizzard")),
  "identity":v("relic","An object made personal","An original ceremonial object can be desired for expression, collection or belonging.","Several kinds of cosmetic value","IDENTITY",["Expression","Fantasy","Collection","Social meaning"],["This is my taste","This is my character","This completes a set","This says something"],"branch","These motives can overlap. Cosmetic describes mechanical scope, not how much an appearance matters.",shop),
  "time":v("market","Two routes to an object","An imagined market shows the long material route and a shorter exchange route.","Compare the complete routes","OWNERSHIP",["Play / craft","Purchase","Trade","Constraints"],["Time and materials","Currency commitment","Another player","Slots, waits, prerequisites"],"balance","Convenience has to be evaluated against the actual unpaid alternatives and remaining constraints.",shot("legacy-poe-store","Path of Exile store showing purchasable offerings","A historical Path of Exile store provides the commercial context. The chapter’s stash-tab claim is sourced to developer documentation.","Grinding Gear Games")),
  "power":v("arena","An advantage in context","An original duel asks what a purchased option changes in the encounter.","Two acquisition routes","THE REWARD",["Encounter","Uncertainty","Market search","Exchange"],["Act within the game","Resolve the outcome","Find an available item","Acquire through a transaction"],"balance","A market can compete with the activity that gives its goods meaning. This diagram does not claim manipulated drop rates.",shot("legacy-d2-item","Diablo II item attributes and requirements","Item properties show why acquisition routes can matter to play. This is a Diablo II comparison image, not a Diablo III auction-house capture.")),
  "what-things-cost":v("market","The balance left behind","An original coin chamber separates an item’s price from the currency that remains.","Four quantities at checkout","CASH ≠ TOKENS",["Existing balance","Item price","Pack purchase","Remaining balance"],["What I already hold","What the item needs","What cash must leave","What stays in the system"],"sequence","The interactive illustration holds the starting balance at zero and compares one pack at a time.",tokens),
  "two-key-lock":v("relic","Two keys for one vault","An original twin-lock vault separates permission to claim from the earned resource.","Unlock, earn, claim","TWO REQUIREMENTS",["Platinum","Catalog access","Earned Favor","Claimed reward"],["Paid currency","First requirement","Second requirement","Spend Favor to claim"],"sequence","A simplified historical example. The earning increment and claim price are invented.",shot("legacy-favor-tutorial","Diablo IV Favor Tokens tutorial","The historical tutorial distinguishes a held balance from what can be earned after spending tokens.")),
  "abstraction-and-surface":v("observatory","A transaction in pieces","An original viewing chamber separates four windows that must form one understandable decision.","Can the player explain it?","COMPREHENSION",["Ownership","Effort","Deadline","Cash and balance"],["What becomes mine?","What remains to do?","What can expire?","What leaves and remains?"],"branch","These are proposed comprehension checks. Visual hierarchy can be observed; spending effects require measurement.",shot("legacy-d4-confirm","Diablo IV purchase confirmation interface","This historical confirmation labels the cosmetic FREE, states a weapon-type restriction and shows the remaining Platinum balance. A zero-price claim still uses the purchase interface.")),
  "does-it-work":v("citadel","What the world leaves with you","A traveler leaves an original citadel carrying knowledge beyond its visible counters.","Four kinds of evidence","VALUE",["Behavior","Experience","Business","Causality"],["What did people do?","How did it feel?","What value and cost?","What caused the change?"],"branch","Each instrument answers a different question. Use their differences to improve the interpretation.",shot("legacy-d4-char-select","Diablo IV seasonal information over character selection","The owner’s return to a character-selection screen provides one concrete case, rather than a population result.")),
};

chapterVisuals["shape-of-money"].screenshot = {"asset": "legacy-d4-shop-grid", "alt": "Diablo IV cosmetic storefront with bundles and a refresh timer", "caption": "Diablo IV’s cosmetic shop. A historical offer within a game that also sells its base release and expansions.", "credit": "Blizzard", "afterParagraph": 3};

chapterVisuals["six-games"].screenshot = {"asset": "legacy-d4-corridor", "alt": "Diablo IV character in the Hell-Touched Corridors", "caption": "Diablo IV, Hell-Touched Corridors. One encounter sits inside a game with several distinct kinds of paid addition.", "credit": "Blizzard", "afterParagraph": 3};

chapterVisuals["the-reset"].screenshot = {"asset": "d4-seasonal-tooltip", "alt": "Diablo IV Seasonal Character tooltip states that the character becomes Eternal at the end of the season", "caption": "Diablo IV character selection, 1 October 2026. The tooltip says seasonal characters move to Eternal after the season.", "credit": "Blizzard", "afterParagraph": 3};

chapterVisuals["why-people-play"].screenshot = {"asset": "legacy-social", "alt": "Diablo IV social interface", "caption": "Diablo IV’s social interface. An invitation begins the practical work of turning separate players into a shared evening.", "credit": "Blizzard", "afterParagraph": 3};

chapterVisuals["play-beyond-score"].screenshot = {"asset": "legacy-indika-pray", "alt": "INDIKA shows a Hold LT to pray prompt in a red-lit scene", "caption": "INDIKA pairs a prayer prompt with a score. The player performs the ritual through a held input.", "credit": "Odd Meter / 11 bit studios", "afterParagraph": 2};

chapterVisuals["familiar-verbs"].screenshot = {"asset": "legacy-d2-combat", "alt": "Diablo II combat near the Cairn Stones with Rakanishu", "caption": "Diablo II, near the Cairn Stones and Rakanishu. Enemies and terrain give familiar attacks their immediate context.", "credit": "Blizzard", "afterParagraph": 2};

chapterVisuals["anatomy-of-loop"].screenshot = {"asset": "legacy-d4-corridor", "alt": "Diablo IV character in the Hell-Touched Corridors", "caption": "Diablo IV, Hell-Touched Corridors. The encounter connects immediate combat to a character’s longer development.", "credit": "Blizzard", "afterParagraph": 3};

chapterVisuals["loot-table"].screenshot = {"asset": "legacy-d2-item", "alt": "Diablo II item tooltip", "caption": "A Diablo II item tooltip. The useful object is a combination of properties, not simply a rarity label.", "credit": "Blizzard", "afterParagraph": 3};

chapterVisuals["the-checklist"].screenshot = {"asset": "legacy-season-rank", "alt": "Diablo IV Death Awakening season ranks interface with a time remaining indicator", "caption": "Diablo IV’s historical Death Awakening season screen places remaining time beside progression.", "credit": "Blizzard", "afterParagraph": 3};

chapterVisuals["access"].screenshot = {"asset": "d4-campaign-state", "alt": "Diablo IV campaign selection with an Endgame recommendation and locked expansion entries", "caption": "Diablo IV campaign selection, 1 October 2026. Locked entries reflect this account’s expansion access.", "credit": "Blizzard", "afterParagraph": 2};

chapterVisuals["identity"].screenshot = {"asset": "legacy-d4-shop-grid", "alt": "Diablo IV shop with cosmetic bundles, a refresh countdown and an Ancient Hydra preview", "caption": "Diablo IV appearance bundles and a shop-refresh countdown. Historical offers and prices.", "credit": "Blizzard", "afterParagraph": 3};

chapterVisuals["time"].screenshot = {"asset": "legacy-poe-store", "alt": "Path of Exile store showing purchasable offerings", "caption": "Path of Exile’s store. Its paid conveniences operate alongside the game’s equipment and trading systems.", "credit": "Grinding Gear Games", "afterParagraph": 3};

chapterVisuals["power"].screenshot = {"asset": "diablo-three-items", "alt": "Diablo III rare and legendary boots shown in equipment comparison panels", "caption": "Diablo III equipment comparison, reproduced from Blizzard’s 2016 retrospective. The stats describe the object; finding it and buying it can produce different experiences.", "credit": "Blizzard Entertainment · Nevalistis, 2016", "afterParagraph": 2};

chapterVisuals["what-things-cost"].screenshot = {"asset": "legacy-d4-platinum", "alt": "Diablo IV Platinum packs with cash prices from the owner’s Canadian-dollar store", "caption": "Historical Diablo IV Platinum packs, priced in Canadian dollars.", "credit": "Blizzard", "afterParagraph": 3};

chapterVisuals["two-key-lock"].screenshot = {"asset": "legacy-favor-tutorial", "alt": "Favor Tokens tutorial explains that players can hold 99 tokens, spend them and earn more", "caption": "The Favor tutorial explains a held-balance limit of 99. Spending makes room to earn again.", "credit": "Blizzard", "afterParagraph": 3};

chapterVisuals["abstraction-and-surface"].screenshot = {"asset": "legacy-d4-confirm", "alt": "Diablo IV purchase confirmation interface", "caption": "This Diablo IV confirmation marks the appearance FREE, names a weapon-type restriction and displays the remaining Platinum balance.", "credit": "Blizzard", "afterParagraph": 3};

chapterVisuals["what-decides"].screenshot = {"asset": "outer-wilds-signalscope-prototype", "alt": "Outer Wilds early signalscope facing Riebeck", "caption": "Outer Wilds signalscope during development, 2016. Mobius added distance information to distinguish a nearby object from a signal beyond it.", "credit": "Mobius Digital · 2016 design article", "afterParagraph": 3};

chapterVisuals["does-it-work"].screenshot = {"asset": "legacy-d4-char-select", "alt": "Diablo IV Season Info popup over the owner’s character selection screen", "caption": "Diablo IV’s character selection introduces the seasonal route beside an existing character.", "credit": "Blizzard", "afterParagraph": 3};
