"""initial schema

Revision ID: 0f1db0936876
Revises: 
Create Date: 2026-02-05 23:46:31.354593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f1db0936876'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pinterest_account_stats_monthly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('calendar_month', sa.Date(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('engagements', sa.Integer(), nullable=False),
    sa.Column('outbound_clicks', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_name', 'calendar_month', name='uq_pinterest_monthly_account_month')
    )
    op.create_index(op.f('ix_pinterest_account_stats_monthly_account_name'), 'pinterest_account_stats_monthly', ['account_name'], unique=False)
    op.create_index(op.f('ix_pinterest_account_stats_monthly_calendar_month'), 'pinterest_account_stats_monthly', ['calendar_month'], unique=False)
    op.create_index(op.f('ix_pinterest_account_stats_monthly_id'), 'pinterest_account_stats_monthly', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('groups', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pinterest_account_stats_monthly_id'), table_name='pinterest_account_stats_monthly')
    op.drop_index(op.f('ix_pinterest_account_stats_monthly_calendar_month'), table_name='pinterest_account_stats_monthly')
    op.drop_index(op.f('ix_pinterest_account_stats_monthly_account_name'), table_name='pinterest_account_stats_monthly')
    op.drop_table('pinterest_account_stats_monthly')
    # ### end Alembic commands ###
